### PR TITLE
Add computation id and audience id to engage stats

### PR DESCRIPTION
**Pull request by VenkataNeeharikaKondipati**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by JusteenRandev — APPROVED** [review]

**Comment by VenkataNeeharikaKondipati** [comment]
> Hi @VenkataNeeharikaKondipati please let me know when you'd like a review of this PR. When are you aiming to have this deployed?

@joe-ayoub-segment need to some E2E testing for this change, I am OOO today, will test it out on Monday for Tuesdays deployment. Thanks

**Comment by joe-ayoub-segment** [comment]
Thanks @VenkataNeeharikaKondipati - the deploy is tomorrow. I'll deploy it if: 
- CI checks all pass
- Someone from the Actions team has reviewed and approved it
- The "Ready for Release" label is applied

I won't have time to review it before the deploy tomorrow (I'm based in EMEA), so you might want to ask another member of my team to review+approve. Please ping them in #integrations-actions-collab

**Comment by VenkataNeeharikaKondipati** [comment]
> Thanks @VenkataNeeharikaKondipati - the deploy is tomorrow. I'll deploy it if:
> 
> * CI checks all pass
> * Someone from the Actions team has reviewed and approved it
> * The "Ready for Release" label is applied
> 
> I won't have time to review it before the deploy tomorrow (I'm based in EMEA), so you might want to ask another member of my team to review+approve. Please ping them in #integrations-actions-collab

Thanks @joe-ayoub-segment I spoke to my manager, we want to release this in the first week of Jan'24

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @VenkataNeeharikaKondipati this PR has been deployed.

**Pull request merged**
