### PR TITLE
Yahoo: added enable_batching and cleaned up error messages

### PR DESCRIPTION
**Pull request by longstoryshort**
1. added enable_batching and batch_size parameters to enforce max batch size of 1000 events
2. improved error message that is displayed when Engage Space Id setting does not pass validation
3. combined 2 GDPR mapping fields into 1 field to ensure the 2 settings are displayed in next to each other in the UI

## Testing
Tested locally with Actions Tester and HTTP requests.

- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @longstoryshort thanks for raising this PR for Yahoo. Can you please remove the changes to the non Yahoo files please?

**Comment by joe-ayoub-segment** [comment]
hi @longstoryshort and @seg-leonelsanches , 
Just checking if you want this PR deployed? There are some changes for another Integration in there. Could you remove them please?

**Comment by seg-leonelsanches** [comment]
> hi @longstoryshort and @seg-leonelsanches , Just checking if you want this PR deployed? There are some changes for another Integration in there. Could you remove them please? The next deploy is Wednesday.

Hi @joe-ayoub-segment. They are just generated code. I just ran the commands on the README.md file.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @longstoryshort and @seg-leonelsanches this PR has been deployed !

**Pull request merged**
