### PR TITLE
May23 main

### PR DESCRIPTION
**Pull request by KWLandry-acoustic**
_A summary of your pull request, including the what change you're making and why._

refactored to handle exceptions, Audiences, 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — CHANGES_REQUESTED** [review]
Hi Kip, 

I'm OK with approving the PR but a couple of minor things need to be done so CI will pass. 

1. tests are failing (see screenshot below). You can run the tests with this command: 
yarn jest --testPathPattern='./packages/destination-actions/src/destinations/acoustic' 

2. When you throw an IntegrationError you need to provide all 3 parameters. 
There are examples in the code where you are just passing a single parameter. 

Have a look at the types of [errors](https://github.com/segmentio/action-destinations/blob/main/packages/core/src/errors.ts) you can throw. It might make sense to use one of the other types. 

Also, have a look at which [response codes](https://github.com/segmentio/action-destinations/blob/main/packages/core/src/errors.ts#L27) will trigger Segment to do a retry. 

Thanks,
Joe

**Comment by KWLandry-acoustic** [comment]
Hi Joe, 
Corrected tests, all run successfully,
Also, made sure each Throw was correctly stated, with all three params or in the case of the retryable, confirmed there were only two, 
Kip

**Comment by joe-ayoub-segment** [comment]
Thanks @KWLandry-acoustic - I'll run the CI now.

**Review by joe-ayoub-segment — APPROVED** [review]
Looks good now. tests pass.

**Comment by joe-ayoub-segment** [comment]
Hi @KWLandry-acoustic this PR has been deployed.

**Pull request merged**
