### PR TITLE
DevRev  Action Destination V1

### PR DESCRIPTION
**Pull request by RtpChris**
This PR is for the beginning of the DevRev destination with the first two core actions fully implemented.

createWork - creates a ticket (support request) or Issue against a particular Part in DevRev.  Uses Dynamic fields to populate with the user's org data

createRevUser - a rev user is a customer or lead in the DevRev app.  This action allows users to create mappings that will create a rev user with or without a comment ang tag whenever the mapped action happens.

We utilize the Segment Actions framework to take action in their DevRev org when a particular Segment event is sent to it.  

This will allow DevRev and Segment users to do things like:
* When a user requests a demo, create work (ticket or issue) with the details
* When a user fills out a form, create a RevUser (lead) object

### About DevRev

DevRev is a business software company that brings developers (dev) and customers (rev) together in the era of product-led growth. The company is building an API-first dev-centric CRM that leverages data, design, and machine intelligence to empower devs to build, support, and grow their revs. In times of anemic NPS and high customer churn, DevRev strives to create the world's most customer-centric companies led by happy developers

## Testing

Tested the actions using a test org on DevRev side and the action tester.  Ensured that all the settings properly created the correct objects and applied the correct tags/comments/etc

- [ X ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ X ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @RtpChris thank you for raising this PR for a new Integration!

To help me review this properly, would you be available to meet with me to discuss the core use-cases, the events to be sent, and the identifiers required by your platform?

You can schedule a call with me using this Calendly link: http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

**Comment by RtpChris** [comment]
Absolutely!  I scheduled a call for Monday at 9 EDT

**Comment by joe-ayoub-segment** [comment]
Notes from PR review: 


Every request in the createRevUser Action will result in 4 HTTP requests to DevRev’s platform
This could cause timeouts
Chris indicated that DevRev should be able to handle spikes in traffic
There is no way to reduce the number of HTTP requests
Joe recommends refactoring the DevRev API if possible ;)  
Presets
Chris doesn’t want Presets configured
Comments
Please remove any unnecessary comments from code
Tests pass
Please remove the console.log from the test
createWork Action
Should expand the defaultSubscription to include an event name
Should change the default for work title field
title: {
label: 'Work Title',
description: 'The title of the work to create.',
type: 'string',
required: true,
default: {
'@if': {
exists: { '@path': '$.properties.work_title' },
then: { '@path': '$.properties.work_title' },
else: { '@path': '$.event' }
}
},
},
Priority field doesn’t need to be dynamic
priority: {
label: 'Priority',
description: 'The priority of the work to create.',
type: 'string',
required: true,
choices: [
{ value: 'p0', label: 'P0 - Critical' },
{ value: 'p1', label: 'P1 - High' },
{ value: 'p2', label: 'P2 - Medium' },
{ value: 'p3', label: 'P3 - Low' }
],
default: 'p2'
},
Type field doesn’t need to be dynamic
type: {
label: 'Type',
description: 'The type of the work to create.',
type: 'string',
required: true,
choices: [
{ value: 'issue', label: 'Issue - Work created by automations' },
{ value: 'ticket', label: 'Ticket - Customer request for assistance' }
],
default: 'issue'
}
Consider adding a field to capture contact details for the reporter who raised the ticket
createRevUser Action
Add a defaultSubscription
Update Description to explain what happens if the user already exists
Update email fields to the following: 
email: {
label: 'Email',
description: "The user's email address.",
type: 'string',
required: true,
default: {
'@if': {
exists: { '@path': '$.traits.email' },
then: { '@path': '$.traits.email' },
else: { '@path': '$.properties.email' }
}
},
},
Update fullName field and add firstName and lastName fields
fullName: {
label: 'Full Name',
description: "The user's full name.",
type: 'string',
required: false,
default: {
'@if': {
exists: { '@path': '$.traits.name' },
then: { '@path': '$.traits.name' },
else: { '@path': '$.properties.name' }
}
},
},
firstName: {
label: 'First Name',
description: "The user's first name.",
type: 'string',
required: false,
default: {
'@if': {
exists: { '@path': '$.traits.first_name' },
then: { '@path': '$.traits.first_name' },
else: { '@path': '$.properties.first_name' }
}
},
},
lastName: {
label: 'Last Name',
description: "The user's last name.",
type: 'string',
required: false,
default: {
'@if': {
exists: { '@path': '$.traits.last_name' },
then: { '@path': '$.traits.last_name' },
else: { '@path': '$.properties.last_name' }
}
},
},

**Comment by RtpChris** [comment]
Thanks @joe-ayoub-segment - quick question on `first_name` and `last_name` - is that the right format or is it `firstName` and `lastName`? The (traits documentation)[https://segment.com/docs/connections/spec/identify/#traits] has the camel case version (`firstName` and `lastName`) as the reserved fields, so I just want to make sure I have the right default format

**Comment by RtpChris** [comment]
I've integrated the rest of the changes, and put in the names as snake-case to match the notes here to make the deploy for tomorrow

**Review by joe-ayoub-segment — APPROVED** [review]
Thanks for applying the changes we discussed. I've a couple minor changes I'll add post this merge.

**Comment by joe-ayoub-segment** [comment]
Hi @RtpChris this PR has been deployed. 
I'll email you next steps. 
regards,
Joe

**Pull request merged**
