### PR TITLE
Add more Fullstory settings

### PR DESCRIPTION
**Pull request by dja**
Adds other Fullstory settings for configuring the `fullstory-browser-sdk` to allow for custom domain specification and other features supported by the SDK.
https://github.com/fullstorydev/fullstory-browser-sdk?tab=readme-ov-file#initialize-the-sdk
https://help.fullstory.com/hc/en-us/articles/18612999473175-How-to-send-captured-traffic-to-FullStory-using-Custom-Endpoints

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @dja - thanks for raising this PR. 
Is there code missing from the PR? All I see are some added Setting definitions, but the logic to make use of those definitions is missing from the code. 
Can you please check / clarify?
Kind regards,
Joe

**Comment by dja** [comment]
> hi @dja - thanks for raising this PR. Is there code missing from the PR? All I see are some added Setting definitions, but the logic to make use of those definitions is missing from the code. Can you please check / clarify? Kind regards, Joe

Hi Joe,
This is my first time contributing to the codebase and wasn't able to generate types or find anywhere else to setup the browser destination for the new settings definitions. Do you have any recommendations on what else is needed?

Thanks!

**Comment by joe-ayoub-segment** [comment]
Hi Daniel,

There's a couple of things to do:

1. (Done) You added some new field definitions.
2. You need to update the generated-types.ts file by running this command:
     ./bin/run generate:types
3. In the perform() function code block you'll need to make use of the new
field definitions.

Have a look through this video to get an understanding of how to build an
Integration with Segment.
https://www.loom.com/share/d39a43b187f04945a80253b852979766
Also, here is a video which covers some basics about Segment.
https://www.loom.com/share/a447434a439e419db5493c66b24e4378

Have a look at the videos and if you still can't figure it out or it's
taking too much time to figure it out please let me know and we can
schedule a call.

Best regards,
Joe

**Comment by joe-ayoub-segment** [comment]
hi @dja - just checking if this PR is something you still want to proceed with?

**Comment by dja** [comment]
> hi @dja - just checking if this PR is something you still want to proceed with?

Thanks for checking Joe - I think it'd be better if someone else took this on. For now, we've applied a monkey patch on our end to circumvent the limitation.

**Comment by joe-ayoub-segment** [comment]
Thanks @dja - who's the best person to follow up with?

**Comment by dja** [comment]
I believe an engineer from Fullstory has reached out to your team?

**Comment by joe-ayoub-segment** [comment]
> I believe an engineer from Fullstory has reached out to your team?

Hi @dja - I don't believe that anyone has been in touch. Is there someone you can connect me with please? my email is jayoub@twilio.com

**Comment by joe-ayoub-segment** [comment]
hi @dja - I'm going to close this PR due to inactivitly. Feel free to reopen it when you'd like to make progress. 
Best regards,
Joe

**Pull request closed without merging**
