### PR TITLE
[Criteo Audiences] Fix error types and remove internal retry

### PR DESCRIPTION
**Pull request by pharika31**
- Removes internal retry logic.
- Replaces `Error` with `IntegrationError` class.
- [x] Local E2E and unit tests running correctly

### CODE REVIEW

**Comment by brennan** [comment]
@pharika31 Would rebase from master, please? Looks like there's only one new commit but the PR contains all original commits from the previous PR as well. Thanks!

**Comment by brennan** [comment]
Thanks, @MarcDillar and @pharika31! This PR generally looks good to me. We should be able to deploy these changes on Monday, March 28 (since we don't deploy on Fridays). I'll follow up with the team on Slack once the deploy is complete.

**Review by brennan — APPROVED** [review]

**Comment by MarcDillar** [comment]
Hi @brennan! We just spotted an issue in our code, due to the `throwHttpErrors` request option being `true` by default.
We fixed that and updated the unit tests to cover this case as well.
Can you review the changes please?
Thank you very much

**Comment by brennan** [comment]
@MarcDillar Would you be able to rebase on master again, please, so I know we have only the most up-to-date changes in this branch? Thanks! cc @pharika31

**Comment by MarcDillar** [comment]
Hi @brennan @mericsson 
We just pushed the following changes:
- removed the retry mechanism we implemented as Segment is already handling retries for HTTP 4xx 5xx errors
- replaced the Errors thrown by the criteo-audiences destination by IntegrationErrors

Can you review and merge these changes please?

**Pull request closed without merging**
