### PR TITLE
Return updated refresh token so that it can be saved

### PR DESCRIPTION
**Pull request by sorich87**
This PR updates Hilo Destination refreshAccessToken method return value to include a new [refreshToken](https://github.com/segmentio/action-destinations/blob/e868e4a7f3f495a3d01660bc8484b3a9da2a011c/packages/core/src/destination-kit/index.ts#L103), so that it can be stored on the Segment side.

Inspired by https://github.com/segmentio/action-destinations/pull/1111 which does the same for Blackbaud Raiser's Edge NXT Destination.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @sorich87 , 
There's a flakey test from another Integration which is causing this PR to fail CI. 
The test has now been fixed, but you will need to get the latest code from main before this PR will pass CI. 
Can you do this please?
Best regards,
Joe

**Comment by sorich87** [comment]
Thanks @joe-ayoub-segment! I updated it.

**Comment by sorich87** [comment]
@joe-ayoub-segment I see it's still failing. Is there something else I need to do?

**Comment by joe-ayoub-segment** [comment]
Looks like a test from another Integration is failing. I'll look into it now.

**Comment by joe-ayoub-segment** [comment]
Hi @sorich87 can you try getting latest files please (again)?

**Comment by sorich87** [comment]
@joe-ayoub-segment done

**Comment by joe-ayoub-segment** [comment]
Hi @sorich87 this PR has been deployed. Please let me know how testing goes!

**Comment by sorich87** [comment]
Thanks, @joe-ayoub-segment! For some reason, it's still not working. I'm looking into it on our end but it's hard to test. Let me know if you have any ideas.

**Comment by joe-ayoub-segment** [comment]
hi @sorich87 , can you schedule a call with me so we can look at this together please?
http://calendly.com/joe_ayoub/integration-workshop 

Best regards,
Joe

**Comment by sorich87** [comment]
@joe-ayoub-segment done! Thanks for your help!

**Pull request merged**
