### PR TITLE
Add recordOnlyThisIFrame setting to FullStory (isOuterScript)

### PR DESCRIPTION
**Pull request by Bogdan1988**
According to our needs running Segment fullstory integration inside an iframe is very valuable feature for us.
Previous PR with the same feature was not merged:
https://github.com/segmentio/analytics.js-integrations/pull/625

So our team decided to ask you about adding recordOnlyThisIFrame feature in new version of the library.

Despite line breaks issues I was ale to run tests locally and generate needed types as well.

Thanks

### CODE REVIEW

**Review by pooyaj — APPROVED** [review]
Looks great! thank you

**Comment by lmakarov** [comment]
@pooyaj thanks for reviewing and merging this!

Any change we could get the "non-actions" version merged as well? https://github.com/segmentio/analytics.js-integrations/pull/625

**Comment by lmakarov** [comment]
@pooyaj What is your release cycle? How soon can we expect this change to go live? Thanks.

**Comment by pooyaj** [comment]
hey @lmakarov! I'll deploy the action based destination on Monday. Also merged the classic destination. Rolling that out is little more involved, but hoping to do that over the next week.

**Pull request merged**
