### PR TITLE
channels-1084: LiquidJS dependency update.

### PR DESCRIPTION
**Pull request by cogwizzle**
_Updating version of liquidjs._

https://segment.atlassian.net/browse/CHANNELS-1084

## Testing

_Should be a transparent yarn test command to ensure the functionality continues to work as expected. Based on coverage reports running the code locally all instances of the liquidjs library have been run through multiple rounds of testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by varadarajan-tw — APPROVED** [review]

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @cogwizzle 
Can you add some proof of testing to the PR please?
I won't be the person deploying it next week as I'll be on PTO

**Comment by cogwizzle** [comment]
> hi @cogwizzle Can you add some proof of testing to the PR please? I won't be the person deploying it next week as I'll be on PTO

I was able to merge onto stage and test via test message flow. I performed liquid variable replacements successfully on email and SMS. This is in addition to the thousands of runs through via the test suite.

**Comment by varadarajan-tw** [comment]
Hey @cogwizzle , PR has been deployed!

**Comment by cogwizzle** [comment]
Thank you!

**Pull request merged**
