### PR TITLE
PE-47 - Merge Algolia Insights

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
## Summary 
 - New Integration for Algolia Insights
 - 3 X Actions
 - Includes unit tests and snapshot tests

## Testing
 - Locally tested using Action Tester
 - Multiple PR reviews with the Partner
 - Unit tests pass

### CODE REVIEW

**Review by sayan-das-in — APPROVED** [review]
LGTM!

**Comment by joe-ayoub-segment** [comment]
hi @wwalser , 
This PR was deployed yesterday. You should be able to start testing it now! 
It's available in Private Beta, so you'll need to access it via a specific URL. 
https://app.segment.com/<YOUR WORKSPACE SLUG>/destinations/catalog/actions-algolia-insights

If you've any follow up questions, including regarding adding meta data and documentation please email partner-support@segment.com.

**Comment by beatrice94** [comment]
Hi Joe, 

We have tested the the destination and it works as expected, so are happy to move on to the next stage. I will send an email through today to get information about adding documentation as well.

We also have some feedback about error handling in Segment. Although we can see that Segment is receiving the events, if there's any failures it doesn't necessarily give you any details about _why_ it failed. This seems to be because it wasn't rejected by the destination itself, but instead Segment didn't forward it on to the destination once it noticed a required property was missing. Is there a way to add some error handling so that we can notify the user that they are missing a required property? I've attached a video for reference but let me know if you require more information.

https://user-images.githubusercontent.com/17920228/220514248-cc34426a-927c-49dc-a7c6-ff3a1151e573.mov

**Comment by wwalser** [comment]
Thanks for the info Joe. Especially about error reporting. I'm glad to hear this is top of mind for the team. 🔥

**Comment by joe-ayoub-segment** [comment]
hi @wwalser , I hope you are well. 
Just checking in to see if you need any assistance with getting your Integration into Public Beta? 
Docs and catalog metadata would need to be completed - and you'd need to be pretty confident that the functionality is correct. 
Kind regards,
Joe

**Comment by wwalser** [comment]
Hi @joe-ayoub-segment, the docs update is in-flight but the engineer who was working on it is on leave at the moment. They may have been trying to get the Segment side of the docs _and_ the Algolia documentation updated at the same time. Let me see if we can push just the Segment side of the changes to you more quickly.

Thanks for the bump 👍

**Pull request merged**
