### PR TITLE
update Koala setting language

### PR DESCRIPTION
**Pull request by mshwery**
This is a non-functional change to update the language used to describe the settings to closer match the current version of our product.

## Testing

No new testing (aside from existing unit tests) required as this is a non-functional change.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by mshwery** [comment]
cc @pooyaj 

also, we're ready to ship the integration! no need to be beta any more :)

**Comment by dlasky** [comment]
@joe-ayoub-segment could we get Matt (OG actions dev!) set up on partner portal?

**Comment by joe-ayoub-segment** [comment]
hi @mshwery  cc @dlasky - best way to do this is for @mshwery to send an email to partner-support@segment.com asking to be set up with access to Partner Portal.

**Comment by mshwery** [comment]
Will do! Thanks @dlasky @joe-ayoub-segment

**Review by silesky — APPROVED** [review]
LGTM

**Review by pooyaj — APPROVED** [review]
🐨🚀

**Comment by pooyaj** [comment]
@mshwery changes are pushed and no more beta 💥

**Comment by mshwery** [comment]
> @mshwery changes are pushed and no more beta 💥 

Amazing. You all rock!

**Comment by dlasky** [comment]
that explains why it wasnt beta when i looked @pooyaj lol

TOOO FAST

**Pull request merged**
