### PR TITLE
[Publish] Registered App Fit and M3ter

### PR DESCRIPTION
**Pull request by sayan-das-in**
This PR registers the following destinations for scheduled publish on July 18, 2023
- App Fit
- M3ter

## Testing

Testing not requires as this PR registers new destination.

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by varadarajan-tw — APPROVED** [review]
Two destinations are registered and available in partner portal!
https://app.segment.com/partner-portal/integration/actions-m3ter/profile
https://app.segment.com/partner-portal/integration/actions-app-fit/profile

**Comment by wkalucki** [comment]
Hi @varadarajan-tw what's the private beta link for the m3ter destination?


https://app.segment.com/partner-portal/integration/actions-m3ter/profile

Return 404

and

https://app.segment.com/dinerbytes/destinations/catalog/actions-m3ter

results in `Couldn't fetch integrations`

**Comment by sayan-das-in** [comment]
@wkalucki Were you able to access the URLs ?

**Comment by wkalucki** [comment]
@sayan-das-in yes, although when trying to add m3ter destination, it results in "We were not able to create a destination, please try again." error

**Pull request merged**
