### PR TITLE
Enable bulk_batching for Iterable updateUser action

### PR DESCRIPTION
**Pull request by marinhero**
Follow up to https://github.com/segmentio/action-destinations/pull/2343 to enable bulk batching for Iterable updateUser action.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks for the PR @marinhero. I'll schedule for review. cc @craigotis

**Comment by joe-ayoub-segment** [comment]
hi @marinhero why is this set to 1001? I understand that Iterable has a max batch size of 1000. Maybe @KakeJopulsky can confirm.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @marinhero and @craigotis . I merged this so that it will go out as soon as someone runs a deploy. 
Let's confirm that 1001 is a safe max batch size for Iterable though, and make a change if it's not.

**Comment by craigotis** [comment]
Thanks @joe-ayoub-segment and @marinhero - also curious about the 1001 (vs. 1000 or some other number), but I think we're fine from an Iterable perspective, since [the docs](https://api.iterable.com/api/docs#users_bulkUpdateUser) only seem to impose a 4MB limit on the request body itself, not necessarily on the number of records it contains.

**Comment by marinhero** [comment]
@craigotis the deploy is now completed. Please delete your existing mapping, create a new one and run a test. Let us know how it goes!

**Comment by craigotis** [comment]
@marinhero That looks _much_ better. We'll continue testing with a larger dataset and keep you posted.
image

**Comment by joe-ayoub-segment** [comment]
hi @craigotis and @KakeJopulsky - 
I"m glad the change seems to be having the desired effect. 

However we need to verify that the max batch size for Iterable is 1001 or under. Is this the case?

**Comment by KakeJopulsky** [comment]
> hi @craigotis and @KakeJopulsky - I"m glad the change seems to be having the desired effect.
> 
> However we need to verify that the max batch size for Iterable is 1001 or under. Is this the case?

The maximum batch size is a 4MB payload, with no limit on the number of records/users per request. Is there anyway to ensure batches stay under 4MBs?

**Comment by joe-ayoub-segment** [comment]
> @joe-ayoub-segment
> 
> > However we need to verify that the max batch size for Iterable is 1001 or under. Is this the case?
> 
> The maximum batch size is a 4MB payload, with no limit on the number of records/users per request. Is there anyway to ensure batches stay under 4MBs?

Hi Jake the only way could be to measure the size of the outgoing payload before sending it. 
However 4MB is very generous and is very unlikely to be breached. 

Segment's max event size is 32kb per event, so 32 X 1001 =  ~3MB. 

I think we're more than save at the 1001 event max limit. 

Thanks for your help.

**Pull request merged**
