### PR TITLE
[Drip] - drip bug fix

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Drip bug fix for Perform. 

## Testing

Destination not yet in use by customers.

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
copy of https://github.com/segmentio/action-destinations/pull/2600 but with fix for Snapshots

**Review by itsarijitray — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
We're in a deploy freeze so next deploy scheduled for 3-Dec

**Comment by joe-ayoub-segment** [comment]
PR deployed - please confirm that you are happy with the change.

**Comment by jacobpmeyer** [comment]
I'm unable to send test events through the frontend.
Screenshot 2024-12-03 at 10 57 05 AM

**Comment by joe-ayoub-segment** [comment]
Hi @jacobpmeyer are there any more reproduction steps you can share please?
This was a pretty small change so I'm surprised with this generic error message. 

How are you attempting to send events?

Best regards,
Joe

**Comment by jacobpmeyer** [comment]
@joe-ayoub-segment For sure. I'm essentially just running the example test event on the event tester page with the addition trait/properties for email depending on the action. Oddly enough the problem is present for both track and identify actions even though the change in this PR was only for the identify action, which makes me think it's not related to the change. It also doesn't display any request/response data in the side panel. The attached screen shot is what I see _after_ sending the event. The error message from the previous screen shot only appears for a second or two before disappearing.
Screenshot 2024-12-04 at 9 11 03 AM

**Comment by jacobpmeyer** [comment]
@joe-ayoub-segment I see this message in the browser console when I click the "Send test event" button
Screenshot 2024-12-04 at 3 39 44 PM

**Comment by joe-ayoub-segment** [comment]
hi @jacobpmeyer - could you schedule a call with me please? https://calendly.com/joe_ayoub/

**Comment by jacobpmeyer** [comment]
@joe-ayoub-segment i heard back from Thomas and got things worked out so I canceled the meeting.

**Pull request merged**
