### PR TITLE
Iterable destination updates

### PR DESCRIPTION
**Pull request by KakeJopulsky**
Updates for the Iterable destination:
* Updates destination auth call
* Removes preferUserId field from all actions
* Removes dataFields input from items and sets additionalProperties: true in commerce actions  
* Adds descriptions to items inputs in commerce actions
* Adds utils.js file that contains date formatting code
* Updates snapshots

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks @KakeJopulsky , I'll have feedback for you in the next 15 mins

**Review by joe-ayoub-segment — CHANGES_REQUESTED** [review]
Few minor things: 

1. Can we rename the Action to be Upsert User instead of Update User?

2. Can we change the name of the event from "Update Cart" to "Cart Updated" so it matches the Segment spec better?

3. For "Track Purchase" Action, do we need to reference "dollars" in the description for the total field? If Iterable only works in dollars that's good, otherwise I think we should be currency agnostic. 

4. I think we shouldn't hardcode the collection of the phone trait. The customer won't know this is happening, and it's the type of 'magic' we don't want to have in our mappings. I tried a few different options on my local machine and think the best option would be to include a completely separate new field just for phone, and then provide default mappings to both '$.traits.phone' or '$.context.traits.phone'. Keen to hear wha you think?

**Comment by KakeJopulsky** [comment]
Thanks for the feedback, @joe-ayoub-segment! I push a few commits per your suggestions.

**Comment by joe-ayoub-segment** [comment]
Hi @KakeJopulsky .  This PR has been deployed.

**Pull request merged**
