### PR TITLE
JLK Accoil Staging Endpoint Implementation

### PR DESCRIPTION
**Pull request by jeremiah-accoil**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @jeremiah-accoil - FYI I had to pull this from today's deploy as there are CI checks failing.

**Comment by jeremiah-accoil** [comment]
> Hi @jeremiah-accoil - FYI I had to pull this from today's deploy as there are CI checks failing.

@joe-ayoub-segment . I will resolve the failings tests and revert. Than

**Comment by jeremiah-accoil** [comment]
> hi @jeremiah-accoil I just noticed that unit tests are failing. Can you take a look please?

Good Daty @joe-ayoub-segment Unit Tests have been fixed. Thank youl

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by jeremiah-accoil** [comment]
Thank you @joe-ayoub-segment

**Pull request merged**
