### PR TITLE
STRATCONN-3246 remove timestamp from LiveRamp filename default

### PR DESCRIPTION
**Pull request by rhall-twilio**
This removes the timestamp from LiveRamp's filename default as it's making their ingestion system less efficient.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment
image

### CODE REVIEW

**Comment by rhall-twilio** [comment]
@joe-ayoub-segment i've marked this PR as `partner-eng-review` to request a definition push on next deploy. please advice alternative otherwise.

**Comment by maryamsharif** [comment]
> @joe-ayoub-segment i've marked this PR as `partner-eng-review` to request a definition push on next deploy. please advice alternative otherwise.

Should we create a new label called `push-required` and add it to PRs?

**Review by maryamsharif — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @rhall-twilio thanks for flagging that you want this deployed. 

I deploy any PR which is labelled with "Ready for release", and will run a push if needed (I review the code of every PR to check if a push is needed). 

You can see details of the upcoming deploy [here](https://segment.atlassian.net/wiki/spaces/~868653230/pages/2496790529/October+2023+-+Actions+Cloud+-+Partner+Weekly+Deploy+Log+Book). I keep a note of which PRs need deploys in that doc. 

Next deploy is Tuesday 10th Oct.

**Comment by joe-ayoub-segment** [comment]
Hi @rhall-twilio this PR has been deployed and pushed

**Pull request merged**
