### PR TITLE
Fullstory web API upgrade

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Upgrading Fullstory Web API 

## Testing

Original PR raised by Partner: https://github.com/segmentio/action-destinations/pull/1838

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @ScottLNorvell are you OK sanity checking this PR please?

**Comment by joe-ayoub-segment** [comment]
I'll copy over my code review to this PR. 

Would it be possible to demonstrate that some testing was done to show that the pre-existing Actions continue to work as before please? And also show some proof of tests for the new Actions?

**Comment by ScottLNorvell** [comment]
> Hi @ScottLNorvell are you OK sanity checking this PR please?

Looks good to me! Thanks for copying this over. I saw your comments and will address today.

**Comment by ScottLNorvell** [comment]
Hi @joe-ayoub-segment. I stacked a PR on top of this with the updates: https://github.com/segmentio/action-destinations/pull/1879

Here are answers to your questions from the closed PR: 

> Comparing the description with the Cloud Integration. Does this also 'Creates a new FullStory user if no user matching the given uid is found.' ?

It's a bit more nuanced than this in the browser. If we get a uid, we do create or update a user but more importantly, we assign that user to the current session. We also take arbitrary custom fields as well as 2 system fields `email` and `displayName`. I looked back at the descriptions and made some small changes (we've moved from calling them "variables" to calling them "properties" 🤷 ) I believe this now encapsulates the broad intent of the integration.

> Is it deliberate the none of these fields are required? (just checking)

I had a look back, and as far as I can tell none are explicitly required. The API's these feed on our end have some flexibility. (i.e. uid only, properties but no uid, or uid + properties). 

> Would it be possible to demonstrate that some testing was done to show that the pre-existing Actions continue to work as before please? And also show some proof of tests for the new Actions?

I fired up the actions tester before and after the changes and all events coalesce into the same end result. I added some additional unit tests (for viewedPage v1) as well as exhaustive unit tests for the v2 methods. Let me know if there is anything else I can do. I couldn't figure out how to actually run this in a browser, fire a segment event, and assert the expected events made it into FullStory. 

> Just looking at the original Actions. Is the camelCaseField() no longer needed in the new Actions?

Great catch. We decided to drop that and leave custom properties mostly untouched. Camel casing is not a hard requirement for our servers.


Let me know if you have any other questions. Thanks for your time reviewing this!

**Comment by joe-ayoub-segment** [comment]
hi @ScottLNorvell the changes look good! Thanks for explaining the testing you did. 
Our web deploys take 24h to roll out - we roll out to specific cohorts of Segment Workspaces first. If you can provide me with a sourceId from your Segment Workspace I can make sure that you'll be able to use the new code before all customers have access to it. 

You can find the sourceId on the Settings Tab of your Source. 

Screenshot 2024-02-14 at 11 41 44

**Comment by ScottLNorvell** [comment]
Hi @joe-ayoub-segment, Great news!

Here is my source id: `g821wEy2diLBCr9Taz59KK`

**Comment by ScottLNorvell** [comment]
Hi @joe-ayoub-segment 

I'll be out of town for the first half next week, but my colleague @sabrina-li (https://github.com/sabrina-li) will handle smoke testing this once it's available to our source.

**Comment by joe-ayoub-segment** [comment]
hi @ScottLNorvell I've pinned your Segment Source (with Source ID = g821wEy2diLBCr9Taz59KK ) to the latest version, in case you wanted to do a test.  
I'll be rolling out the latest version to all customers later today. 
Best regards,
Joe

**Comment by sabrina-li** [comment]
Hi @joe-ayoub-segment ,
Thank you for the update! I just checked the source `g821wEy2diLBCr9Taz59KK` but didn't see the new actions (V2) listed in the FullStory destination (receiving from the source above). Is there any additional steps needed for me to test it using that source?
Thank you!
Sabrina

**Comment by joe-ayoub-segment** [comment]
Hi @sabrina-li - my bad - I can see the new code is pushed out however it also requires a DB migration before it will be usable. 
I'm going to roll out to all customers prior to running the DB migration. I'll notify you once it has been done. 

Best regards,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @ScottLNorvell and @sabrina-li 
The PR has been fully deployed. 
I can see the changes on my local Segment Workspace. 
Could you please test and let me know if everything looks good?

image

**Comment by sabrina-li** [comment]
HI @joe-ayoub-segment,
I can see the V2 actions and have tested with our test source, they work as expected for all three actions.
Thanks for all your help!
Sabrina

**Comment by joe-ayoub-segment** [comment]
Thanks for confirming @sabrina-li !

**Pull request merged**
