### PR TITLE
SD-96619 - Platform Key Insider

### PR DESCRIPTION
**Pull request by esezerguven**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @esezerguven - approved! 
Just waiting for CI to pass.

**Comment by esezerguven** [comment]
> Hi @esezerguven - approved! Just waiting for CI to pass.

hi @joe-ayoub-segment some of tests are failed. IS there anything that I can check?

**Comment by esezerguven** [comment]
@joe-ayoub-segment hello could you please check here 🙏

**Comment by joe-ayoub-segment** [comment]
Hi @esezerguven - We've paused our deploys for the moment due to an internal issue. I don't think we'll be deploying for a couple of days at least. It might be next week before we can get this change out. Apologies for any inconvenience.

**Comment by esezerguven** [comment]
@joe-ayoub-segment seems test are passed. So we are waiting the next week for deployment are we ? Could you please update

**Comment by joe-ayoub-segment** [comment]
> @joe-ayoub-segment seems test are passed. So we are waiting the next week for deployment are we ? Could you please update

That's correct @esezerguven . We didn't do a deploy this week. Next Tuesday is the next scheduled deployment.

**Comment by joe-ayoub-segment** [comment]
Hi @esezerguven this PR has been deployed. Can you confirm that you are happy with the change please?

**Comment by esezerguven** [comment]
> Hi @esezerguven this PR has been deployed. Can you confirm that you are happy with the change please?

Thank you @joe-ayoub-segment for informing. I have informed our QA team to make live test. I am working on another task currently on my local. however when I tried to go 
image
It gives error of 
image
I have confirmed that it also happens on my colleagues. I have also checked all is updated in my local after deployment. Can it be related with latest deployment ?

**Comment by joe-ayoub-segment** [comment]
Thanks for pointing this out to me Sezer,

I was able to reproduce the issue and can confirm that it is a bug. We'll
get it fixed ASAP. I'll let you know once it has been done.

Best regards,
Joe

**Comment by joe-ayoub-segment** [comment]
> > Hi @esezerguven this PR has been deployed. Can you confirm that you are happy with the change please?
> 
> Thank you @joe-ayoub-segment for informing. I have informed our QA team to make live test. I am working on another task currently on my local. however when I tried to go image It gives error of image I have confirmed that it also happens on my colleagues. I have also checked all is updated in my local after deployment. Can it be related with latest deployment ?

Hi @esezerguven , 
Confirming that there is a bug with the Action Tester. We'll get it fixed. I'll ping you once it's been resolved.

**Pull request merged**
