### PR TITLE
PE-88 Snap products - add product array support for Snapchat Conversions API 

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Update the Snapchat Conversions API Destination so that it can handle a Segment products array. 

Specifically a new array field added to support this type of structure: 

"products": {
  {"product_id": "12345", "price": 100, "category": "toys", "brand": "Hasbro", "quantity": 5},
  {"product_id": "98765", "price": 76, "category": "games", "brand": "Mattel", "quantity": 2},
} 

## Testing

Tested using the Actions Tester connected to Snapchat. Test results [here](https://docs.google.com/document/d/1KzLcancj-NbgR9IZHgJ6_LRzm0mkNckGimJFPUZQkAk/edit).

Unit test added to test that arrays of products are accepted.

### CODE REVIEW

**Review by dcasey-sc — CHANGES_REQUESTED** [review]
Hey Joe, thanks for all the hard work on this. Just a few nitpicks regarding code style.

**Comment by dcasey-sc** [comment]
@joe-ayoub-segment given that none of the comments above are logical issues we can handle them in another PR so we don't block the customer if desired. Let me know what you think.

**Comment by joe-ayoub-segment** [comment]
> @joe-ayoub-segment given that none of the comments above are logical issues we can handle them in another PR so we don't block the customer if desired. Let me know what you think.

Thanks @dcasey-sc , let's go ahead with the PR then, thanks for verifying everything!!

**Comment by joe-ayoub-segment** [comment]
Testing after adding new field allow price calculation to be toggled

TEST 1: calculates price from product array details. 
image
image

**Comment by joe-ayoub-segment** [comment]
TEST 3: excluding product array falls back to using individual fields 
image
image

**Review by dcasey-sc — APPROVED** [review]
LGTM, thanks @joe-ayoub-segment

**Comment by joe-ayoub-segment** [comment]
Hi @dcasey-sc this PR has been deployed!

**Pull request merged**
