### PR TITLE
extend actions-s3 batch size max to 100k

### PR DESCRIPTION
**Pull request by apacker**
Increasing the maximum batch size for actions-s3 to 100k. This is to support larger batch sizes for this destination for Fidelity.

## Testing

This was tested end-to-end in stage in conjunction with the new batching feature in Centrifuge. We were able to achieve 100k batches delivered to s3:

image

```
wc -l < 2024-12-02T19-44-43-081Z.csv
  100000
```

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [x] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @apacker - just checking in on this PR. Do you intend for it to be reviewed and deployed? it's still in draft. 
Cheers,
Joe

**Comment by apacker** [comment]
Hi @joe-ayoub-segment - this PR will just be used for some load testing in the staging environment.

**Comment by apacker** [comment]
@joe-ayoub-segment we will be moving forward with this increase and will need a review.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
PR deployed

**Pull request merged**
