### PR TITLE
[Recombee (Actions)] Fix bugs, improve descriptions

### PR DESCRIPTION
**Pull request by mstieranka**
Hi, this is a PR fixing the things mentioned in the code review in https://github.com/segmentio/action-destinations/pull/2429, since that already got merged.

I think it would be best if this was only merged once our internal testing in Private Beta concludes, so that we can fix all the issues that we find there.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @varadarajan-tw - FYI looks like the required field check is failing for this PR. There are no new required fields being added, just an update to descriptions for some required fields.

**Comment by varadarajan-tw** [comment]
@joe-ayoub-segment - The check is failing because this branch doesn't have the latest changes from main and that includes template required for this check. Merging main to this branch would make this go away.

**Comment by mstieranka** [comment]
rebased onto the current main, thanks for the heads-up

**Comment by joe-ayoub-segment** [comment]
hi @mstieranka do you want this PR to be deployed? If so please convert from Draft and let me know when to review.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @mstieranka PR deployed. Please confirm that you are happy with the changes.

**Pull request merged**
