### PR TITLE
PT-623: Adding preset for iterable

### PR DESCRIPTION
**Pull request by baguirr**
Adding a preset for iterable for JSM
## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

For testing I created a Journey where a user enters a Journey if "User Performs an event" with a destination of Iterable. When the Journey is created a call is then made to the CreateSubscriptionWithPreset endpoint which will use the presetId created through this repository (deployed using actions-cli push command). Through CreateSubscription I was able to confirm that the PresetId is working and was able to verify that our application emits an event to iterable. 

iterableJSMPage

IterableOrkesRed

IterableResult

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @baguirr thanks for raising this PR. 
I'm the person who reviews PRs for Partner owned Integrations. 
Could we catch up for 15 minutes so I can get some info about this change please?
Feel free to schedule via my Calendar (jayoub@twilio.com) or via this Calendly link: http://calendly.com/joe_ayoub/integration-workshop

**Review by nick-Ag — APPROVED** [review]

**Comment by nick-Ag** [comment]
Hey, could you add some screenshots from your stage testing in the PR description? Otherwise approved 🚢

**Comment by joe-ayoub-segment** [comment]
We'll deploy on Tuesday 13-Feb.

**Comment by joe-ayoub-segment** [comment]
hi @baguirr this PR has been deployed. Please verify that all looks good!

**Pull request merged**
