### PR TITLE
Properly retrieve email

### PR DESCRIPTION
**Pull request by slavivanov**
Hello, this PR is updating the paths where the user's email can be found.

For "identify" events, first look in `traits.email`, then in `context.traits.email`.

For "track" and "pageview" events, first check `context.traits.email` and then `properties.email`.

Does this make sense?

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @slavivanov , thanks for the PR. It will be deployed with our next deploy.

**Comment by slavivanov** [comment]
It seems the failing tests are not related to this PR, but please let me know if you need something from my side.

**Comment by joe-ayoub-segment** [comment]
That's correct @slavivanov - an Engineer is working to fix the build. After that I'll rerun CI and merge.

**Comment by joe-ayoub-segment** [comment]
Hi @slavivanov , 
The issue has been fixed, but you'll need to pull in the latest files from segmentio/action-destinations main branch before your PR will pass CI. Can you do this please?
Cheers,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @slavivanov this PR has been deployed. Please let me know if everything looks good!

**Pull request merged**
