### PR TITLE
 Adding Group support for customerio -Rename identifier field names

### PR DESCRIPTION
**Pull request by kishoredevarasettyn**
Field names were changed for the group and identify in the destination. Following changes are made to support the field name changes. Changes are tested end to end using https://app.segment.com/dev-center/actions-tester

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @kishoredevarasettyn , thanks for submitting this PR :)
Just 1 question: will this change impact customers who are already using this Integration in any way? Is so, could you explain the impact please?
Thank you!

**Comment by kishoredevarasettyn** [comment]
> 
Hi @joe-ayoub-segment , this action is not being used by customers yet. This action is hidden right now. We are planning to unhide this once this change also goes in.

**Comment by joe-ayoub-segment** [comment]
Hi @kishoredevarasettyn , 
Would you be available to catch up and take me through how this works please?
You can schedule a call with me here calendly.com/joe_ayoub/integration-workshop

Kind regards,
Joe

**Comment by kishoredevarasettyn** [comment]
> Hi @kishoredevarasettyn , Would you be available to catch up and take me through how this works please? You can schedule a call with me here calendly.com/joe_ayoub/integration-workshop
> 
> Kind regards, Joe

I have scheduled a call for next Tuesday(earliest available on your calendar 🙂)

**Review by joe-ayoub-segment — APPROVED** [review]
Met with @kishoredevarasettyn who explained that this change is for an Action which is not currently available for use (it's been blocked by Robert Hall). 

Ran tests locally and they passed.

**Pull request merged**
