### PR TITLE
Add Revend Destination

### PR DESCRIPTION
**Pull request by muboeira**
This pull request adds a new destination based on G4 Google Analytics to the package segment destinations. The destination is designed to help online store owners detect anomalies with user behavior and collected data.

## Testing

I have made the tests based on G4 destination and to account for the new destination I made changes, but overall they remain largely unchanged.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment(can't do it)

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @muboeira , 
Thanks for raising this PR! 
Given this is a new Integration would you be available for a face to face meeting? You can schedule a call with me using this Calendly link: http://calendly.com/joe_ayoub/integration-workshop

Purpose is to get an understanding of your use-cases so that I can provide better feedback on the PR. 

Kind regards,
Joe

**Comment by alexmreis** [comment]
@joe-ayoub-segment call booked with me and @muboeira, looking forward to discussing our use cases with you :) Might help if you get acquainted with what our product does, https://revend.ai. See you soon!

**Comment by joe-ayoub-segment** [comment]
Reviewed every file in this PR and am happy with it. 
Summary: 
 - All Actions from GA4 Destination have been duplicated. 
 - client_id is now a required field
 - Some functionality has been removed such as data_stream_type and app_instance_id fields 
 - All URLs are sending data to Revend
 
Here's an example diff from one of the Actions (all other actions follow the same pattern). Revend on the left, GA4 on the right
 
image

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @alexmreis this PR has been deployed.

**Pull request merged**
