### PR TITLE
Added preset for Customer.io jsm step event

### PR DESCRIPTION
**Pull request by taricjain**
- Adding mapping for new Journeys Step Transition track event for JSM

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @taricjain , 

I removed the Ready for Release label as I didn't hear back from you. 
This is a Partner owned Integration so I'm meant to be across any change that happens. 
Could we sync to discuss please? I'll message you on Slack. 
Thanks,
Joe

**Review by apareek-twilio — APPROVED** [review]
LGTM

**Review by apareek-twilio — APPROVED** [review]
LGTM

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @taricjain PR deployed and pushed. Please confirm it looks good!

**Pull request merged**
