### PR TITLE
Schematic - field changes

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Minor changes to fields

## Testing

Tested locally with Actions Tester

### CODE REVIEW

**Comment by jasdeepg** [comment]
@joe-ayoub-segment did not this go through today? was hoping we could get this going

**Comment by joe-ayoub-segment** [comment]
Hi @jasdeepg - our deploy has been postponed to tomorrow. Apologies for any inconvenience. I'll message once it has been done.

**Comment by jasdeepg** [comment]
@joe-ayoub-segment got it! thank you :)

**Comment by joe-ayoub-segment** [comment]
hi @jasdeepg - PR deployed! Please confirm that you are happy with the change!

**Comment by jasdeepg** [comment]
@joe-ayoub-segment are we sure this was deployed? not seeing the changes in the destination

**Comment by joe-ayoub-segment** [comment]
Ahh craps - wow I'm not sure what happened there. I merged this but it seems like the merge didn't happen. 
Apologies for that @jasdeepg . Usually we only merge just as we kick off a deploy. I'll merge this now so that there won't be a risk that it will be missed with next Tuesday's deploy. 

Apologies again,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @jasdeepg - PR deployed. Please confirm the change looks good!

**Comment by jasdeepg** [comment]
will do, thanks @joe-ayoub-segment ! a few more changes i need to make that i found in testing with one of our partners.

**Comment by joe-ayoub-segment** [comment]
Thanks @jasdeepg  - have you raised a new PR for these changes yet?

**Pull request merged**
