### PR TITLE
[Cli Push] - Fixes `TypeError: Cannot read property 'hidden' of undefined`

### PR DESCRIPTION
**Pull request by nick-Ag**
When a new destination is registered, but before it's first `push`, the `existing` object being referenced will be undefined. This causes a `TypeError: Cannot read property 'hidden' of undefined`
This was reported here: https://github.com/segmentio/action-destinations/pull/1219/files#r1221927012

This PR safely references the `existing` object when pushing options. 
I also included a VS code launch option for the push command to support debugging.

## Testing
Since this issue occurs after a new destination is registered and before it's first push I reproduced by manually setting the object: `existing = undefined`. This is to avoid actually registering a new dummy integration in our stage DB.

Repro:
Screenshot 2023-06-09 at 4 29 37 PM

With fix, the push command doesn't error:
Screenshot 2023-06-09 at 4 30 43 PM

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by nick-Ag** [comment]
@joe-ayoub-segment - Mind reviewing this one?

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @nick-Ag , looks like another code review is needed from segmentio/build-experience-team

**Review by pooyaj — APPROVED** [review]

**Review by marinhero — APPROVED** [review]

**Comment by SyedWasiHaider** [comment]
Can we make sure these changes also make it to the internal cli if necessary? cc @NolanChan @valerieernst

**Comment by nick-Ag** [comment]
> Can we make sure these changes also make it to the internal cli if necessary? cc @NolanChan @valerieernst

Looks like Nolan did this a while back: https://github.com/segmentio/action-cli/pull/110
Maybe time to completely deprecate the push command on this repository so we only have one place to change?

**Comment by NolanChan** [comment]
@nick-Ag we definitely want to deprecate the old cli! My high-level plan is to 
1. Confirm that actions-cli works for all three commands in production - will pair with Joe/Pooya next week to confirm
2. Once confirmed, I'll rip out the CLI command from this repository

**Comment by nick-Ag** [comment]
Closing since this command will be removed from this repo shortly.

**Pull request closed without merging**
