### PR TITLE
[fb capi] external id update

### PR DESCRIPTION
**Pull request by nick-Ag**
Updating the defaults for the `user_data.externalId` field. This update applies across all FB CAPI actions.
Removed the `properties` from `properties.anonymousId` and `properties.userId`

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

Pushed to stage and successfully tested the mapping. 
Screen Shot 2021-12-01 at 9 29 11 AM

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by mshwery** [comment]
I don't think users can get back to this state via the UI by themselves. If we want coalesce support I recommend you ensure it's enabled in the UI too!

**Comment by nick-Ag** [comment]
> I don't think users can get back to this state via the UI by themselves. If we want coalesce support I recommend you ensure it's enabled in the UI too!

@dlasky Is coalesce for object properties a known issue for build experience?

**Comment by dlasky** [comment]
@nick-Ag wasn't on my radar. I think we need to think long and hard about allowing that as it will potentially cause performance problems as our volume grows

**Comment by nick-Ag** [comment]
> @nick-Ag wasn't on my radar. I think we need to think long and hard about allowing that as it will potentially cause performance problems as our volume grows

Should we avoid using `coalesce` for object properties? Users would have to reconfigure the action to get that `coalesce` back as Matt mentioned. That workaround seems clunky

**Comment by dlasky** [comment]
yeah its clunky, but also as soon as we start nesting directives we've opened up a whole can of worms, like technically it 'works' as far as mapping kit can process it correctly, but we do have to think about the impact we might have on the platform from doing so and carefully balance that against the user need.

as far as the UI experience, its probably relatively straightforward to add that to object, but there may be some trickyness with the state for the individual keys.

**Review by dlasky — APPROVED** [review]

**Pull request merged**
