### PR TITLE
Update default Ripe cloud mode endpoint

### PR DESCRIPTION
**Pull request by simpajj**
Updating the default endpoint of the Ripe cloud mode destination.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @simpajj I've approved this PR. 
Please note that this only updates the default URL for customers who install the Integration after the deploy happens. 
Customers who already have the Integration installed won't get this new default URL. 

Is that OK with you?

**Comment by simpajj** [comment]
> Hi @simpajj I've approved this PR. Please note that this only updates the default URL for customers who install the Integration after the deploy happens. Customers who already have the Integration installed won't get this new default URL.
> 
> Is that OK with you?

Thanks @joe-ayoub-segment 
Yeah, that's OK. We're redirecting from the old endpoints, so all good!

**Comment by joe-ayoub-segment** [comment]
hi @simpajj - PR deployed. Please confirm that you are happy with the changes!

**Comment by simpajj** [comment]
> hi @simpajj - PR deployed. Please confirm that you are happy with the changes!

Hi @joe-ayoub-segment 
It still shows the old endpoint when setting up new destinations. 

Screenshot 2024-03-20 at 09 09 20

**Comment by joe-ayoub-segment** [comment]
Thanks for checking @simpajj . It's working now. 
Best regards,
Joe

image

**Pull request merged**
