### PR TITLE
updating presets to point to V2 Actions

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Fullstory preset update to point to V2 Actions
Original code change raised by Partner here: https://github.com/segmentio/action-destinations/pull/1838

## Testing

Tested locally.

### CODE REVIEW

**Comment by ScottLNorvell** [comment]
> Hi @ScottLNorvell are you OK sanity checking this PR please?

LGTM @joe-ayoub-segment makes sense to separate these, thanks!

**Comment by joe-ayoub-segment** [comment]
Hi @ScottLNorvell this PR has been deployed. Can you confirm that it looks good please?

**Comment by joe-ayoub-segment** [comment]
image

**Comment by ScottLNorvell** [comment]
Looks good to me @joe-ayoub-segment! Sorry for the delay, I'm making the changes to the other one now!

**Pull request merged**
