### PR TITLE
minor changes to Avo

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
PR to update the customer facing display name for the Avo Action. 
Also creating a new field 
 
## Testing

Tested locally with Actions Tester.

### CODE REVIEW

**Comment by bjornj12** [comment]
LGTM

**Comment by joe-ayoub-segment** [comment]
hi @bjornj12 this should be going out today!

**Comment by joe-ayoub-segment** [comment]
PR deployed.

**Comment by joe-ayoub-segment** [comment]
Can you confirm that the change looks good please? @bjornj12

**Pull request merged**
