### PR TITLE
convert date strings to Airship-friendly format

### PR DESCRIPTION
**Pull request by jumpingGrendel**
Airship Attributes API expect dates to be in a specific format. This PR evaluates strings used in SetAttributes and if they are valid ISO1806 dates, converts them to the correct format for this purpose.

## Testing
- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by NolanChan** [comment]
Could we get a test against the action itself and sending a date through it? Should be good after that!

**Comment by jumpingGrendel** [comment]
@NolanChan added action tests

**Comment by jumpingGrendel** [comment]
@NolanChan @marinhero unclear if there's something I need to do about the partner hold label on this PR...?

**Comment by joe-ayoub-segment** [comment]
Hi @jumpingGrendel , 

I'm just back from PTO so will pick this up. I've not yet had a chance to get through all my email, so there might be other items related to Airship that I need to catch up on. 

Shall we schedule a call for later this week to get me up to speed on all-the-things?

My Calendly is up to date here http://calendly.com/joe_ayoub/integration-workshop 

Kind regards,
Joe

**Comment by jumpingGrendel** [comment]
thanks @joe-ayoub-segment I had already grabbed a slot on Friday for that exact purpose :raised_hands:

**Comment by joe-ayoub-segment** [comment]
Hi @jumpingGrendel , 
I ran the code to try and test it out. 
Noticed that all 'attributes' are passed through this new function. Code seems to work for me. If a string doesn't evaluate into a real date then it is set to null. 

Is that the expected behavior?
Thanks
Joe

**Comment by jumpingGrendel** [comment]
> Hi @jumpingGrendel , I ran the code to try and test it out. Noticed that all 'attributes' are passed through this new function. Code seems to work for me. If a string doesn't evaluate into a real date then it is set to null.
> 
> Is that the expected behavior? Thanks Joe

yes @joe-ayoub-segment . See https://github.com/segmentio/action-destinations/pull/1437/files#diff-357e3f99496a14c0d7d4b8c2299ad6efdd6aae860945c64b3638cdee2afa0865R126

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @jumpingGrendel this PR has been deployed. Please check and let me know how everything looks!

**Comment by jumpingGrendel** [comment]
@joe-ayoub-segment looks good thanks!

**Pull request merged**
