### PR TITLE
Algolia insights integration

### PR DESCRIPTION
**Pull request by wwalser**
This PR adds a new [Algolia](https://www.algolia.com/) Action Destination. This destination sends data to our [Insights API](https://www.algolia.com/doc/rest-api/insights) and consumes all of the currently supported event types for that interface. Additionally, I've tried to provide good default mappings for all fields based on [Segment's V2 Ecommerce Events Spec](V2 Ecommerce Events).

This destination is similar to [Algolia's existing destination](https://segment.com/docs/connections/destinations/catalog/algolia-insights/), utilizes Segement's modern API interfaces and is (hopefully) more helpful to customers.

## Testing
No particular notes here. I've manually tested locally using serve as well as writing unit tests. As the perform function for all of these destinations is very simple, test tests mostly feel like testing configuration — for which I see there are already tests. If there's anything additional you'd like to see, or common pitfalls you've noticed other teams falling into I'd be happy to learn more.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hey @wwalser , I thought I recognised that handle (we worked together at Atlassian years ago ;) 
How are you? 

I'll be taking care of the PR shortly.

**Comment by joe-ayoub-segment** [comment]
Awesome job @wwalser , it looks really great. 

We've recently updated our new Integration submission process to include a face to face call. The purposes if to be able to provide more relevant, contextual feedback. This is typically what we cover: 

1. Overview of the customer experience / use-cases. i.e how does the customer benefit from using the Integration, and how will they use it.
2. Walk through the code (which looks good from my initial review)
3. End to end test - i.e sending event data using the Action Tester to an instance of the Destination for each Action you've defined, and checking that the entities in the Destination update correctly. 

Would you be open to catching up to do this? 
I'm based in EMEA (Ireland) so am in the same timezone as the UK. I have slots available to meet tomorrow (Thursday 18th) between 13:00 and 16:00 Ireland/UK time, and then Friday between 10:00 and 17:00 Ireland/UK time. 

If so please share your email address and available time slots to joe.ayoub@segment.com 
Hopefully chat soon

**Comment by wwalser** [comment]
I am, indeed, in Australia so the times you initially gave would be a difficult lift.

I'm out of the office until early next week but I'll cut a video ASAP.

> Another topic I wanted to ask you about was with respect to the required fields such as index, position, queryID.

These fields are required and our API clients make it simple to persist this data across pages (web) and surfaces (mobile). Once we have the destination created, we'll build toward automatically sending these events either directly to our Insights API (for customers not using a message bus) or to Segment.

Give me a few days to cut a video and I'll drop a link here. Cheers!

**Comment by wwalser** [comment]
@joe-ayoub-segment demo video: https://drive.google.com/file/d/1EQQWozwN9bp5j_4h_56ZJmLBAfEntnwI/view?usp=sharing

**Comment by joe-ayoub-segment** [comment]
Amazing, thank you @wwalser ! I'll review tomorrow.

**Comment by wwalser** [comment]
> does anonymousId really need to be a required field? If it does that's OK, but you'll generally only get anonymousId values passed from client side (browser or mobile) SDKs. You generally won't get anonymousIds sent from back end services. Happy to chat about this if you're unclear.

Interesting. I assumed, based on the sample data provided in the test kit, that an anonymousID would always be present. I presumed that this was created and maintained by Segment on behalf of the customer. 

I'll do a loop on my end to see if this is critical. I expect some form of identity across calls is. The queryID may be sufficient.

> In the video you shared the inbound payload's 'type' value was set to 'view'. 

That's just test data provided by the action tester tool which spins up when you run `./bin/run serve`. Since the action tester doesn't bother validating that portion of the inputs, I didn't bother changing it. The default mapping provided by each of my actions:

Conversion Events: `type = "track" and event = "Order Completed"`
Product Clicked Events: `type = "track" and event = "Product Clicked"`
Product Viewed Events: `type = "track" and event = "Product Viewed"`

> Would you consider adding some presets?

Happy to add these, I do note that they don't appear to be documented. Should I make anything of the fact that these appear to be used exclusively by browser destinations and not by any of the destination-actions?

Screenshot 2023-01-29 at 1 14 36 AM

I presume users can still change the mapping values even if they are included in a preset? A very similar role is filled by "default" mappings which I've provided for each field https://github.com/segmentio/action-destinations#default-values.

**Comment by joe-ayoub-segment** [comment]
Hi @wwalser , 
Thanks for the detailed response. 

presets are often configured for Cloud Mode Destinations (not just browser ones). You can find some examples [here](https://github.com/segmentio/action-destinations/blob/main/packages/destination-actions/src/destinations/amplitude/index.ts#L14). 

I recorded a short [video](https://drive.google.com/file/d/1fLu1qYSfFQ6ixqkYj4RU_w5Qih66irFH/view?usp=share_link) discussing the anonymousId and userId. You'll get one or the other or both in every Segment API call. 

Let me know once you have updated the PR and I'll get it merged and deployed!

**Comment by joe-ayoub-segment** [comment]
Hi @wwalser , checking to see if you need any assistance with this.

**Comment by wwalser** [comment]
Hi @joe-ayoub-segment! Yup, just tied up with other tasks so had another engineer lend a hand.

- Thanks for the info about anon id and user id. I've made changed on that front. Please let me know if the new approach seems more appropriate. The core insight is that we require _some_ user id, not specifically the Segment userId or anonymousId — either of them will do.
- I've also added presets as requested.

**Comment by wwalser** [comment]
Just bumping this thread @joe-ayoub-segment

**Comment by joe-ayoub-segment** [comment]
Thanks @wwalser ack your PR update. I'm catching up after some time off. Will review ASAP.

**Review by joe-ayoub-segment — APPROVED** [review]
Looks good. I'll merge this now, and it will deploy tomorrow. 

Couple of minor things but these could be done in the next PR: 
1. spelling mistake in conversion events description: "Successful product purcahses which can be tied"
2. Should really implement the testAuthentication. This is used to check that the customer has provided ApiKey and apiId values which work. The function is called when the user provides these settings in the UI and will inform the customer if their credentials don't work.

**Comment by joe-ayoub-segment** [comment]
Hi @wwalser , I just noticed that the tests are failing. Could you fix these please? 

If you have time it would be great if you could also do the following: 

1. spelling mistake in conversion events description: "Successful product purcahses which can be tied"

2. Should really implement the testAuthentication. This is used to check that the customer has provided ApiKey and apiId values which work. The function is called when the user provides these settings in the UI and will inform the customer if their credentials don't work.

If you can get these done in your Wednesday work day I'll approve and the deploy will happen Wednesday evening Irish time.   Otherwise the next deploy is Wednesday 15th.

**Comment by wwalser** [comment]
I've fixed the spelling error and implemented a testAuthentication method.

I do not see any test failures in my code (`yarn cloud test --testPathPattern=src/destinations/algolia-insights`). When I run the full cloud test suite I do see some error coming from other destinations.

**Comment by joe-ayoub-segment** [comment]
Thanks @wwalser , you're correct there was an issue yesterday which was caused by a test from another Integration which was failing (it was hitting a URL which should have been mocked). 

However I just ran the tests again and did get some errors from your Integration. Looks like the timestamps from the snapshots are not matching. 

image

**Comment by joe-ayoub-segment** [comment]
Hi again @wwalser , 
There is an optimization which could be made which would make sense. I'll leave you to decide if you want to do it or not: 

You could replace the userId and anonymousId fields with a single field called 'userToken' (or whatever Algolia uses as a name for its user identifiers). 

You could then have a default mapping which looks like this: 

  default: {
    '@if': {
      exists: { '@path': '$.userId' },
      then: { '@path': '$.userId' },
      else: { '@path': '$.anonymousId' }
    }
  } 

The behaviour here is such that the anonymousId will only be used if there is no userId in the payload. The customer can always specify their own mapping anyway. 

Happy to go with what you've got if you don't want to apply this change though. 
Nearly there :). 
Joe

**Comment by wwalser** [comment]
The tests were passing for us and not for you because the dates that we pass in the test file don't declare a timezone which means every timezone needs a different timestamp in their snapshot file for the tests to pass:

```
--- a/packages/destination-actions/src/destinations/algolia-insights/conversionEvents/__tests__/snapshot.test.ts
+++ b/packages/destination-actions/src/destinations/algolia-insights/conversionEvents/__tests__/snapshot.test.ts
@@ -18,7 +18,7 @@ describe(`Testing snapshot for ${destinationSlug}'s ${actionSlug} destination ac
     nock(/.*/).persist().put(/.*/).reply(200)
 
     const event = createTestEvent({
-      timestamp: new Date('December 17, 2022 03:24:00').toISOString(),
+      timestamp: new Date('December 17, 2022 03:24:00 UTC').toISOString(),
       properties: eventData
     })
```

I'll raise another PR to fix this.

**Comment by joe-ayoub-segment** [comment]
Thanks @wwalser that's correct. I fixed it in the [other PR](https://github.com/segmentio/action-destinations/pull/1027) already. 

Let me know if you are OK with the change I made (merging userId and anonymousId fields together into a single field called userToken?

We didn't get the deploy out yesterday, it should happen today though. I'll notify you once it's done.

**Comment by wwalser** [comment]
> Let me know if you are OK with the change I made (merging userId and anonymousId fields together into a single field called userToken).

Yes, I hadn't seen the docs for if then mappings. Great!

> I fixed it in the https://github.com/segmentio/action-destinations/pull/1027 already. 1027 is the PR which will be deployed.

I was not familiar with `Z` indicating a time zone. So I learned something and yes, that does fix the problem. Thanks!

**Comment by beatrice94** [comment]
Hi @joe-ayoub-segment just wanted to check if it's possible to have a Browser Destination separate from a Destination Action?

**Comment by joe-ayoub-segment** [comment]
Hi @wwalser , 
Yesterday's deployment was cancelled and pushed to next week. I'll let you know when I have a date for it. 

Hi @beatrice94 , I'm not sure I understand your question properly. Could you elaborate please? If you like you can schedule a call with me to discuss: http://calendly.com/joe_ayoub/integration-workshop 

You can build a "Device Mode Destination" if you like? This works much the same way as the "Cloud Mode Destination" you've just built, but the logic / transformation runs in the browser. A Segment Device Mode Destinations will load your client side library into the browser, and will trigger events using your Javascript library. 

You can see the current list of Device Mode Destinations [here](https://github.com/segmentio/action-destinations/tree/main/packages/browser-destinations/src/destinations). 

Does this answer your question?

**Pull request merged**
