### PR TITLE
[Braze] Add MultiStatus Response support

### PR DESCRIPTION
**Pull request by sayan-das-in**
This PR adds MultiStatus support to Actions Braze (Cloud Mode).

## Testing
Tested with Unit Tests, Local env and Stage env.
Test doc available [here](https://docs.google.com/document/d/1So_MebIuZyQwtEIss88mft3VPl0lkIk-n62agLnEAeA/edit).

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by maryamsharif** [comment]
I see that you have added the multistatus to the V2 actions. Do you plan to also add it to the original (V1) actions?

**Comment by marinhero** [comment]
Hey Sayan, this seems like a sizable change and while you don't change the event-delivery side of things, reporting does change. Can you provide evidence of testing in Staging to make sure we all understand how the destination will change? An example can be found [here](https://docs.google.com/document/d/1Aq_kkOabFYItCCr-gFth2tO5ixUKoMaBjn0wGLRmCtw/edit#heading=h.62hz0yn78b36).

**Comment by sayan-das-in** [comment]
Hi @marinhero and @maryamsharif the change has been made to both the V1 and V2 Actions. Since the action definitions call methods defined in `utils.ts`, the change is made there.

**Review by marinhero — APPROVED** [review]

**Review by maryamsharif — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @sayan-das-in PR deployed

**Pull request merged**
