### PR TITLE
Mixpanel destination: use user-agent for browser data

### PR DESCRIPTION
**Pull request by spjtls9**
Previously Mixpanel used `device_manufacturer` for detecting Safari. However, this parameter is no longer passed as part of payload for the current `analysis` APIs. This PR remove dependency on `device_manufacturer` and rely on user-agent to parse browser data.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @spjtls9 , acknowledging your PR! I'll schedule some time to review ASAP.

**Review by joe-ayoub-segment — CHANGES_REQUESTED** [review]
Hi @spjtls9 , 
Thank you again for taking time to catch up to discuss this PR. Here are notes from the call: 

Change is to correct the browser type value being sent to Mixpanel. 
Joe explained that this will result in a change of behaviour for customers who already have the Integration configured, but Sonya indicated that the change is a correction in data collection, and that customers should be happy about this. 

Sonya may make a tweak to the PR, and will notify Joe. Joe happy to approve PR.

**Review by joe-ayoub-segment — APPROVED** [review]
Met with Sonya and reviewed. Sonya said this will correct some behaviour which customers expect.

**Comment by joe-ayoub-segment** [comment]
Hi @spjtls9 , this PR has now been deployed. Please verify and let me know if there are any issues!

**Comment by spjtls9** [comment]
@joe-ayoub-segment our support team was able to verify that the fix is working as expected. Thank you!

**Pull request merged**
