### PR TITLE
[CCP-322] Remove 'to name' from engage sendgrid destination action

### PR DESCRIPTION
**Pull request by mattcullenmeyer**
https://segment.atlassian.net/browse/CCP-322

The to.name field is not required per SendGrid API documentation
https://docs.sendgrid.com/api-reference/mail-send/mail-send
image

## Testing

I confirmed emails sent without the to.name field are still delivered successfully
image

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks for the PR @mattcullenmeyer . I'll review ASAP.

**Comment by joe-ayoub-segment** [comment]
Hi @mattcullenmeyer , 
Thanks for raising this PR. 
Looks like CI is failing - might also be a UI Github bug as it's not showing me the logs. 
We did have a flakey test earlier today which was causing PRs to fail CI - so it might be worth getting the latest from the main branch into your PR. 
Could you do this please?
Cheers,
Joe

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @mattcullenmeyer this PR has been deployed. Please let me know how testing goes!

**Comment by mattcullenmeyer** [comment]
Everything looks good - thank you!

**Pull request merged**
