### PR TITLE
Fix/test authentication

### PR DESCRIPTION
**Pull request by Hagej**
_A summary of your pull request, including the what change you're making and why._

The testAuthentication function now properly parses errors and gives clearer directives of how to fix issues.

## Testing

The existing test has been modified to match the actual response structure of when an incorrect API key is entered

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by sayan-das-in — APPROVED** [review]
Following changes were made in this PR

- Updated descriptions in Test Cases
- Updated description in a field
- Exception handling was updated in testAuthentication method

There are no new fields added. LGTM!!!

**Comment by joe-ayoub-segment** [comment]
note: deployed by Sayan 24-Apr

**Comment by joe-ayoub-segment** [comment]
hi @Hagej , this PR was deployed a couple weeks ago. Does it look OK to you?

**Comment by Hagej** [comment]
Hi @joe-ayoub-segment 
Yes, this looks OK!

**Pull request merged**
