### PR TITLE
anoymousId in segment to be tracked as device_id in mixpanel

### PR DESCRIPTION
**Pull request by dneralla**
just as the way user information is dependent on anonymousID and userId in segment, in the new version of idmerge its dependent on device_id and user_id in mixpanel

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @dneralla , acknowledging your PR! I'll schedule time to get this reviewed ASAP.

**Comment by dneralla** [comment]
Thanks lemme know if anything is needed from my end .

**Comment by joe-ayoub-segment** [comment]
Hi @dneralla , I'm just getting to this PR and the other Mixpanel PRs (https://github.com/segmentio/action-destinations/pull/1035 and https://github.com/segmentio/action-destinations/pull/1033 now.

Given this is a change to an identifier (device id, anonymousId) would you be available to catch up with me to discuss the change, the potential impact on customers, etc? Would you be OK scheduling a call with me via this [Calendly URL](http://calendly.com/joe_ayoub/integration-workshop)?

Your colleague [Sonya Park](https://github.com/spjtls9) also raised a PR for this Integration, so I'm wondering if we could meet at the same time to discuss all the changes together?

**Comment by dneralla** [comment]
Yeah I am down to meet at the same time.

**Comment by joe-ayoub-segment** [comment]
hi @dneralla , Sonya scheduled a call for 1pm Irish / UK time. She mentioned that she doesn't think that this time will work for you. You are welcome to join if you are available, otherwise probably best to schedule a different call.

**Comment by dneralla** [comment]
@joe-ayoub-segment I scheduled call on monday 9:30 am.

**Comment by joe-ayoub-segment** [comment]
Notes from call with @dneralla . 

Only a single line of logic is changing, and only in a single Action. The following field value currently gets sent to Mixpanel

`$device_id: payload.device_id`

This PR changes the value being sent for this field to the following: 

`$device_id: payload.anonymous_id`

I asked @dneralla if this change would have any impact on customers who are already using the Integration and he said that there would be no impact because: 
- the field is a private field that customers can't view
- the value from this field is not currently used for anything in Mixpanel
- The Mixpanel team plan to start using the value from this field in the near future only. 

The background behind this change is that the Mixpanel team wants to be able to allow Mixpanel to automatically merge anonymousId and userId identifiers into the same profile. The change in this PR is a prerequisite for the remaining work they need to do to allow this. 

@dneralla indicated that he'd also like to apply this same change the older 'Classic' Mixpanel Integration. I suggested he raise a partner-support@segment.com ticket to find out how best to get the Classic Mixpanel Integration changed. 

We also ran unit tests locally and they passed.

**Review by joe-ayoub-segment — APPROVED** [review]
Had a face to face meeting with @dneralla . See notes here https://github.com/segmentio/action-destinations/pull/1031#issuecomment-1437374300

**Comment by joe-ayoub-segment** [comment]
Hi @dneralla , 
Would you be able to rebase your PR please? There might be some merge conflilcts which are not auto mergable. 
Thank you!

**Comment by dneralla** [comment]
Yup will do

**Comment by dneralla** [comment]
rebased main

**Comment by dneralla** [comment]
@joe-ayoub-segment  Lemme know if u need anything else from me. if not can we get this merged ?

**Comment by joe-ayoub-segment** [comment]
Hi @dneralla, this PR has now been deployed. Please verify and let me know if there are any issues!

**Pull request merged**
