### PR TITLE
Add company enrichment to Upollo

### PR DESCRIPTION
**Pull request by cayden-uw**
This PR optionally adds company information enrichment to Identify requests. This includes company name, industry and employee count. 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)

### CODE REVIEW

**Review by pooyaj — COMMENTED** [review]
I'm curios about the use-case for this change. Are we trying to enrich the events that eventually will go to Segment? Looks like we are no longer sending identify calls to Upollo, but instead fetch company info and just enrich the events 🤔

**Comment by cayden-uw** [comment]
Hey @pooyaj, This does still send the event to Upollo it just adds optional enrichment to the Segment event when it does.

**Comment by cayden-uw** [comment]
Any concerns @pooyaj? Happy to grab time to chat if you do

**Comment by pooyaj** [comment]
@cayden-uw Some concern here as mutating the event in a destination could cause unpredictable behavior. If user has multiple destinations, some of them may see the `traits.company` property and some may not, and that behavior is not predictable, as destinations are running asynchronously and not in a predictable order. 

There are other examples of action destinations in the repo that use `context.updateEvent` to mutate the event, but those destinations use `lifeCycleHook` property to make sure they run before regular destinations.

Happy to chat and find an alternative solution if mutating the event is particularly important in this case.

**Comment by cayden-uw** [comment]
Thanks @pooyaj for the thoughtful feedback. It sounds like if I add the lifeCycleHook and set that to enrichment then that would solve the issue of unpredictable behaviour for other destinations? 

If that is the case I will update this PR to that affect now.

**Comment by cayden-uw** [comment]
@pooyaj I updated the lifecycle hook. Let me know if any other changes are needed!

**Comment by pooyaj** [comment]
@cayden-uw sorry for the delay, was getting second opinion on the approach 😄 In this case changing the lifecycleHook of the existing action is not ideal for few reason: 
- It is a breaking change for the destination, as enrichment type actions won't support certain destination features such as destination filters. 
- The enrichment feature will halt the delivery pipeline by making call to the Upollo endpoint and waiting for it to be resolved. 

Is it possible to separate the enrichment logic into its own action that can be optionally turned on by customers? So we will have two actions: 
- `identifyUser` --> which just sends data to Upollo 
- `enrichCompany` --> makes a call to Upollo and enriches the event

**Comment by cayden-uw** [comment]
Thanks for the thoughtful and detailed response @pooyaj. A few things I hadn't thought about when I added this feature originally. 

I have updated the PR to split it into the two actions as suggested

**Comment by cayden-uw** [comment]
@pooyaj let me know if you have any feedback on this or if it is good to go

**Comment by cayden-uw** [comment]
Friendly ping for review

**Review by pooyaj — APPROVED** [review]
🚢

**Comment by cayden-uw** [comment]
Thanks @pooyaj!

**Pull request merged**
