### PR TITLE
Avo update wording based on customer feedback

### PR DESCRIPTION
**Pull request by bjornj12**
Updating the description and label for API key and appVersionProperty name based on feedback from customer to be more clear which key it is and whether it's needed.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by bjornj12** [comment]
hey @joe-ayoub-segment sorry for all the minor updates 🙈

Just a minor update to the wording in the destination settings so its more clear for the customer where to get the API key and when to fill in the `AppVersionPropertyName` field, which is the biggest feedback we've got so far, otherwise the integration is working very nicely 🙌

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by bjornj12** [comment]
@joe-ayoub-segment we will be pushing people into the segment destination with blog posts and hypes today and rest of the week, any chance getting this in soon? 🙏

**Comment by joe-ayoub-segment** [comment]
> @joe-ayoub-segment we will be pushing people into the segment destination with blog posts and hypes today and rest of the week, any chance getting this in soon? 🙏

Hi @bjornj12 ! I'm just starting the deploy work now. It should be live later today (it's a long process). I'll notify you here once it's live. 

Best regards,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @bjornj12 this PR has been deployed - please confirm that it looks good!

**Comment by bjornj12** [comment]
Brilliant @joe-ayoub-segment Thanks! 🤩

**Pull request merged**
