### PR TITLE
Canvas destination

### PR DESCRIPTION
**Pull request by wpride**
[Canvas](http://canvasapp.com/) is an all-in-one data tool that provides data warehousing, ETL, and visualization. Many of our customers use Segment and visualize their events in our tool. We're adding Canvas as a Segment destination so that we can ingest and display our users' events in real-time. 

## Testing

I've added unit tests and tested authentication and each of our actions via the local server (very helpful, thank you!)

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @wpride thanks for raising this PR. 

As it's for a new Integration would you be OK meeting to discuss the use-cases, types of data and user identifiers to be collected please?

You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop

I look forward to hearing from you! 

Kind regards,
Joe

**Review by joe-ayoub-segment — CHANGES_REQUESTED** [review]

**Comment by joe-ayoub-segment** [comment]
Thanks for taking the time to catch up just now @wpride . 
Only a couple minor changes requested. If you can get them in by Wednesday morning I'll get this deployed.

**Comment by joe-ayoub-segment** [comment]
Thanks for making those changes @wpride . Please let me know when you are done and I'll merge. Unfortunately we've missed this week's deploy. Next deploy is Tuesday 7th Nov.

**Comment by wpride** [comment]
Hey @joe-ayoub-segment - thank you so much for the time yesterday, learned a lot! Made the update you suggested.

Re: original timestamp, I tried adding this but the tests were complaining - it looks like this fields isn't in the [`SegmentEvent`](https://github.com/segmentio/action-destinations/blob/main/packages/core/src/segment-event.ts#L108) type here and was admitted by [`createTestEvent`](https://github.com/segmentio/action-destinations/blob/main/packages/core/src/create-test-event.ts#L4). Regardless this isn't necessary for a us so not a blocker.

**Comment by joe-ayoub-segment** [comment]
Hi @wpride - It's not really useful so prob best to leave it out!

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by wpride** [comment]
Hey @joe-ayoub-segment  - sorry for not following up here! Are we good to go?

**Comment by joe-ayoub-segment** [comment]
Hi @wpride we're good - deploying today.

**Comment by joe-ayoub-segment** [comment]
Hi @wpride this PR has been deployed. I'll share next steps and instructions by email

**Pull request merged**
