### PR TITLE
Map full event context in Ripe Cloud Mode

### PR DESCRIPTION
**Pull request by simpajj**
Mapping of the full event context in the Ripe Cloud Mode destination.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by tcgilbert** [comment]
hi @simpajj  - our partner engineer who reviews these PRs is currently out of office but will be back Thursday. If there is absolute urgency behind this PR, or you have any questions, let me know.

**Comment by simpajj** [comment]
> hi @simpajj - our partner engineer who reviews these PRs is currently out of office but will be back Thursday. If there is absolute urgency behind this PR, or you have any questions, let me know.

Hi @tcgilbert 
Thanks for informing us! Do you know when they're back? It's a bit of an urgent one unfortunately.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @simpajj this PR has been deployed

**Comment by joe-ayoub-segment** [comment]
Please confirm the change looks good!

**Comment by simpajj** [comment]
> Please confirm the change looks good!

Looks good on our end! Thanks @joe-ayoub-segment

**Pull request merged**
