### PR TITLE
changing loading for jimo

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Sam to add description

_A summary of your pull request, including the what change you're making and why._

## Testing

Will be tested on Sam's Workspace prior to rollout to all customers.

### CODE REVIEW

**Comment by imsamdez** [comment]
Hey @joe-ayoub-segment,

Had to create another PR since I'm not allowed to push on this branch.
You can find it here : https://github.com/segmentio/action-destinations/pull/2314.

I included the workspace ID in the PR description. Thanks for your help !

**Comment by joe-ayoub-segment** [comment]
Hi @imsamdez I tested this. Please see this video. 
image

If you are OK with this test please let me know so I can deploy on Monday + Tuesday ( to all customers )

**Review by sayan-das-in — APPROVED** [review]

**Comment by imsamdez** [comment]
Hey @joe-ayoub-segment,

Unfortunately, it's doing weird things.
We have tested it with a customer and we can see different issues :

- Sometimes, the loading of the js file is failing which prevent from installing and running Jimo on the page (see screen)
image
- When using the manual init, the first Segment Identify seems to correctly triggers the `sendUserData` action of Jimo integration but next ones won't triggers the `sendUserData` action for some reasons.

I think it would be worth checking this on a call because i'm also having some troubles dealing with our customers patience 😅

**Comment by joe-ayoub-segment** [comment]
Hi Sam,

Let's get on a call ASAP.

If we can't figure it out I'll see if I can schedule a call with one of our
front end Library engineers.

Here is my calendly: https://calendly.com/joe_ayoub/

Thanks,
Joe

**Pull request merged**
