### PR TITLE
[Usermaven] Page Action Added

### PR DESCRIPTION
**Pull request by seeratawan01**
This PR updates the Usermaven destination with additional action for pageview and a minor bug fix with a typo in the anonymous id.
## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @seeratawan01 , acknowledging this PR, thanks for raising. 
I'm just back from PTO but will review as soon as possible. 
Kind regards,
Joe

**Comment by azhard4int** [comment]
> 

Thank you, Joe. Looking forward.

**Comment by seeratawan01** [comment]
Hi @joe-ayoub-segment, 

yes you can merge and deploy the changes.

**Comment by joe-ayoub-segment** [comment]
Thanks @seeratawan01 , 
Actually there are some CI tests failing. Nothing to do with your code though. Could you pull down the latest files from the main Segment branch into your PR please?

**Comment by seeratawan01** [comment]
Hi @joe-ayoub-segment, we are unable to merge rn due to Gihub operations being degraded,  we will be merging it as soon as the GitHub operations are back to normal.

**Comment by seeratawan01** [comment]
@joe-ayoub-segment merged with the latest changes

**Comment by seeratawan01** [comment]
Hey @joe-ayoub-segment, 

Kindly review and merge this PR, we have synced our fork with the latest changes. 

Thanks.

**Comment by joe-ayoub-segment** [comment]
Thanks @seeratawan01 , If CI checks pass then I can merge.

**Comment by azhard4int** [comment]
> Thanks @seeratawan01 , If CI checks pass then I can merge.

Hi Joe,

The synk test is failing because authenticated account is required: `snyk requires an authenticated account. Please run snyk auth and try again.` and the rest of the tests have passed. 

Can we please get this merged?

**Comment by seeratawan01** [comment]
Hi @joe-ayoub-segment, 

This is taking a lot of time and our customers are waiting for the integration. 

How long will it take, as the issue is not from our side?

**Comment by joe-ayoub-segment** [comment]
Hi @seeratawan01 , 

I can merge without snyk passing. As long as the other CI tests pass. 

I had another look through the PR and noticed 2 minor things. You can decide if you want to do anything about them or not: 

1. You're adding an Action to handle page() events, however you are not letting the customer pass the page name as a field. 
2. Screen fields are included in your new page Action. These fields don't make sense in terms of a page. It's probably no harm to leave them in but customers might find it confusing. 

I'm rerunning CI now again to see if it will pass.

**Comment by azhard4int** [comment]
@joe-ayoub-segment 

At the moment, our focus is not on mobile devices. However, we plan to incorporate a feature for screen calls through a separate PR in the upcoming future.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @seeratawan01  and @azhard4int this PR has been deployed. Please check and let me know if everything looks good!

**Comment by azhard4int** [comment]
Hi @joe-ayoub-segment 

We have tested it on our end, everything works fine, but there is small change related to the API payload which Seerat is working on currently, we will create the separate PR for that one.

**Pull request merged**
