### PR TITLE
Qualtrics upsert transaction

### PR DESCRIPTION
**Pull request by drakauskas**
_A summary of your pull request, including the what change you're making and why._

**Additional Qualtrics destination - Upsert Contact Transaction**

- Allows for a transaction to be added to a Qualtrics directory contact using the Qualtrics Public API
- If a contactId is provided, a transaction is added normally using [this](https://api.qualtrics.com/08e5f0bb11170-create-contact-transaction) endpoint 
- If a contactId is not provided, a lookup is done using a [this](https://api.qualtrics.com/c79e78a949572-search-directory-contacts) endpoint
- If a contact is found, transaction is added normally. This search needs to find 1 and only 1 contact, providing all three fields is recommended: extRef, email and phone
- If a contact is not found, one is created using the supplied fields using [this](https://api.qualtrics.com/3f3d5290d19c2-create-directory-contact) endpoint, and the transaction is added normally.

## Testing

Added unit tests and snapshots for the new destination. Tested end to end locally using a Qualtrics instance.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thank you for raising this PR @drakauskas . I'll provide feedback on this as soon as possible.

**Comment by joe-ayoub-segment** [comment]
hi @drakauskas , 
We've updated our process for adding new Integrations and new Actions slightly to include a face to face review. 
Would you be available to meet to run through the following with me please?
1. Explain how customers will use this new Action (what's the use-case etc) and how it works
2. Review the code together and potentially agree any require tweaks. 

I'm based in EMEA (Ireland) so am in the same timezone as the UK. Would you be available to meet tomorrow between 12:00 and 16:00 UK time, or Friday between 10:00 and 17:00 UK time? 

If so please share your email address to joe.ayoub@segment.com and I'll send you an invite.

Looking forward to catching up,
Joe

**Comment by joe-ayoub-segment** [comment]
note: tests pass

**Comment by joe-ayoub-segment** [comment]
See below for notes from face to face review meeting. 

**Settings**
- Add default value to datacenter setting

**testAuthentication function**
- Ensure that the the testAuthentication function returns a boolean value only

**UpsertContactTransation Action**
**Fields**
- Contact id description should refer to “External Data Reference” 
- External Data Reference - consider default to be coalesce(userId, anonymousId)
- Description: provide more verbose description. E.g. creates a ContactTransation and appends it to a Contact, or creates the Contact and then appends the ContactTransation…
- defaultSubscription - provide a different event name following the “Object Action” convection. https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/ 
- For phone, first_name, last_name etc. fields, update the description to explain that it’s the matching Contact object who will get these values updated (and not the Contact Transaction object) 

**AddContactToXMD Action**
- Add link to documentation explaining that Upsert can be achieved by configuring deduplication on the Qualtrics back end 

**Investigate Dynamic Field**
- Consider adding a Dynamic Field if you need/want it. The Actions Tester UI now supports this and the capability does work in production. 

**Presets** 
- Consider if you need to set up Presets (i.e default Actions)

**Comment by carlmlee** [comment]
@joe-ayoub-segment - We have commited the changes discussed on the call and add dynamic fields for the directoryId and applied to both the addContactToXMD and upsertTransaction actions.

**Comment by joe-ayoub-segment** [comment]
Thank you @carlmlee I'll review this tomorrow!

**Comment by carlmlee** [comment]
@joe-ayoub-segment Just wanted to follow up on these changes. Ty

**Comment by joe-ayoub-segment** [comment]
hi @carlmlee , 
Apologies, I'll get to this PR today or tomorrow. Hoping to get the PR merged and deployed this week. 
Kinds regards,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @carlmlee , the changes look good to me. 
I wasn't able to do an end to end test as I don't have a Qualtrics login. I was therefore also not able to test the Dynamic Fields. 

This is in Private Beta so I'd be OK with getting this merged and deployed, and you could test these things yourself after the deployment. Or we could catch up and do one last end to end test prior to deployment. If you'd like to catch up and do that test together please schedule a call http://calendly.com/joe_ayoub/integration-workshop 

Otherwise I can merge the PR and you can test post deployment. 

I'd advise that if you have real customers using the Integration (even though it is in Private Beta) that we do an end to end test together. 

Best regards,
Joe

**Comment by carlmlee** [comment]
@joe-ayoub-segment Thanks for the review. We do not currently have any real customers using this, therefore deploying now and Qualtrics performing end to end testing on it will suffice. Thank you for the diligence on this

**Comment by joe-ayoub-segment** [comment]
Agreed to merge and deploy given there are no real customers using the Integration, and that extensive testing will be done post deploy. 

@carlmlee could we have a shared session post deploy to do an end to end test?

**Review by joe-ayoub-segment — APPROVED** [review]
Approving changes for merge based on: 
1. No 'real' customers using the Integration at the moment
2. testing will be done post deploy (with Joe included)

**Pull request merged**
