### PR TITLE
Insider | SD-107645 | Products ingesting incorrectly

### PR DESCRIPTION
**Pull request by emreisik95**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks for raising this PR @emreisik95 . 

The bulk of the change is linting comment removal, and then there's some data processing changes. 

Can you explain what functionality change is being implemented here please? 
Can you demonstrate that this was tested, and that it won't adversely affect customers who are already using the Integration?


Best regards,
Joe

**Comment by emreisik95** [comment]
> Thanks for raising this PR @emreisik95 .
> 
> The bulk of the change is linting comment removal, and then there's some data processing changes.
> 
> Can you explain what functionality change is being implemented here please? Can you demonstrate that this was tested, and that it won't adversely affect customers who are already using the Integration?
> 
> Best regards, Joe

Hello Joe,

image

We change the above code, because we had below issue. We were update product object with latest product information.

image

A partner raised a flag for that and provide us example payload. According to that we made our tests:

image

And we are getting correct data from segment.

image

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 . There's still some CI checks failing. Are you able to take a look please?

**Comment by emreisik95** [comment]
> Hi @emreisik95 . There's still some CI checks failing. Are you able to take a look please? cc @tcgilbert

Updated the tests.

**Comment by joe-ayoub-segment** [comment]
hi @emreisik95 , snapshots are failing. 
You might be able to fix them by running this command: 

`yarn jest --testPathPattern='./packages/destination-actions/src/destinations/insider' --updateSnapshot`

image

**Comment by emreisik95** [comment]
> hi @emreisik95 , snapshots are failing. You might be able to fix them by running this command:
> 
> `yarn jest --testPathPattern='./packages/destination-actions/src/destinations/insider' --updateSnapshot`
> 
> image

Hello @joe-ayoub-segment,

I am already doing that. I updated the snapshot.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @emreisik95 PR deployed. Please confirm it looks good!

**Pull request merged**
