### PR TITLE
Taboola actions - add alphabetic account id description

### PR DESCRIPTION
**Pull request by eden-ohana**
Change Taboola account id description.
## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by eden-ohana** [comment]
Hi @joe-ayoub-segment could you please review

**Comment by joe-ayoub-segment** [comment]
hi @eden-ohana can you run this command and them commit the change to this PR please

./bin/run generate:types 

Thanks,
Joe

**Comment by eden-ohana** [comment]
@joe-ayoub-segment done
Thanks

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @eden-ohana PR deployed.

**Pull request merged**
