### PR TITLE
Add sprig web integration

### PR DESCRIPTION
**Pull request by bgila**
_A summary of your pull request, including what change you're making and why._

Add Sprig browser destination with handling for identify, track, and alias.

## Testing

**now resolved** ~Running into an issue with UUID generation in the testing harness, still investigating but decided to open this issue/PR in case it's something the team is familiar with https://github.com/segmentio/action-destinations/issues/372~

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
  - **not possible for browser destinations**
- [ ] [Segmenters] Tested in the staging environment
  - **not applicable**

### CODE REVIEW

**Comment by coreyching** [comment]
Looks great! nice job on the initial PR. As discussed offline @bgila to update update the alias action to 'updateUserId' to describe the behavior it'll have in the Sprig platform.

**Comment by bgila** [comment]
ok -- updated the PR with the renamed `updateUserId` event, and added a sign out user action per my discussion with @coreyching. Working on internal docs now, but this is ready to deploy from Sprig's end

**Review by mshwery — APPROVED** [review]
Lgtm. Cc @pooyaj

**Review by pooyaj — APPROVED** [review]
Looks great!

**Comment by bgila** [comment]
rebased to fix `yarn.lock` merge conflict, ready to deploy ASAP!

**Pull request merged**
