### PR TITLE
Add Courier action destination

### PR DESCRIPTION
**Pull request by tk26**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @tk26 thanks for raising this PR for a new Integration. 

I had a quick look and spotted a number of potential issues which warrant a face to face discussion - would you like to schedule a call to discuss please?

http://calendly.com/joe_ayoub/integration-workshop

Kind regards,
Joe

**Comment by tk26** [comment]
> Hi @tk26 thanks for raising this PR for a new Integration.
> 
> I had a quick look and spotted a number of potential issues which warrant a face to face discussion - would you like to schedule a call to discuss please?
> 
> http://calendly.com/joe_ayoub/integration-workshop
> 
> Kind regards, Joe

Hey @joe-ayoub-segment 👋🏼 Thanks for quick response! I wasn't able to find any viable slots this week, do you have anyone else on the team that could jump on a call in pacific timezone for this week? If not I can find something on your calendar next week, I do see viable slots then.

**Comment by joe-ayoub-segment** [comment]
Hi @tk26 - could we catch up next week? 
I'm the only person who reviews external PRs.

**Comment by tk26** [comment]
> Hi @tk26 - could we catch up next week? I'm the only person who reviews external PRs.

I'll check with the team. By any chance we could do this via this thread/PR chat?

**Comment by bwebs** [comment]
hey @joe-ayoub-segment , working with @tk26 on this one. As it might help clarify before the call, Courier's current implementation is a Direct Destination. We need the same functionality (forwarding all requests) but with the ability for our customers to choose which Courier region to apply them to. This changes the domain/endpoint to route the requests. Looking through examples and your docs, this PR is the most straightforward implementation for us.

**Comment by joe-ayoub-segment** [comment]
Thanks for the background @bwebs - makes sense. 
Let's still catch up as I think there are some things to fix in the PR. Chat to you Monday. 
Kind regards,
Joe

**Comment by joe-ayoub-segment** [comment]
Opened new PR here: https://github.com/segmentio/action-destinations/pull/1837

Closing this PR

**Pull request closed without merging**
