### PR TITLE
GRAMA-1249: [Sendgrid/Twilio data Exposing Sources] - Update payload to add user id

### PR DESCRIPTION
**Pull request by xinghaohuang91**
This PR is to add segment userid to sms and email send. 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @xinghaohuang91 and @alfrimpong , 
Thanks for raising this PR @xinghaohuang91 . There is [another PR](https://github.com/segmentio/action-destinations/pull/1266) open for this Integration at the moment, and it refactors a lot of code. 
Are you each aware of each other's PR?

**Comment by joe-ayoub-segment** [comment]
Agreed with @alfrimpong and @xinghaohuang91 to postpone the review of this PR until Albert's [PR](https://github.com/segmentio/action-destinations/pull/1266) has been merged and deployed. This is to reduce the risk of a Sev.

**Comment by joe-ayoub-segment** [comment]
hi @xinghaohuang91 , @alfrimpong 's change has been merged now.

**Comment by joe-ayoub-segment** [comment]
Hi @xinghaohuang91 , 
Is this the refactored PR you'd like me to review / merge / deploy? 
Is so, I can see that there are breaking tests

image

Would you be able to address these please?

**Comment by xinghaohuang91** [comment]
> Hi @xinghaohuang91 , Is this the refactored PR you'd like me to review / merge / deploy? Is so, I can see that there are breaking tests
> 
> image
> 
> Would you be able to address these please?

Yes! Let me check it! Thanks

**Review by joe-ayoub-segment — APPROVED** [review]
Syntactically the change looks good to me. CI passes. 
There's no field changes. 

I'm not able to comment on how this change will affect the data going to Twilio, but I assume you have that well understood @xinghaohuang91 !

**Comment by joe-ayoub-segment** [comment]
Hi @xinghaohuang91 , this PR was deployed last Friday 09-Jun-2023. 
Please take a look and ensure you are happy with the change. 
Best regards,
Joe

**Pull request merged**
