### PR TITLE
Upgrade lerna to 6.0.0 + alpha fixes

### PR DESCRIPTION
**Pull request by dlasky**
Some long overdue quality of life fixes for actions repo

Bumps lerna to the latest version, and changes the alpha command so that it now uses a branch specific pre-id which should prevent 'stepping' on other branches alphas when publishing test versions.

## Testing

Tested by running publish command locally, as well as creating some fake commits to push and exercising the new alpha command.

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by NolanChan** [comment]
@dlasky am I doing this wrong? Whether or not I add a new commit, `yarn alpha` isn't pushing anything up

```
(stage-write/stage:us-west-2:centrifuge-destinations) $ yarn alpha
yarn run v1.22.19
$ lerna publish --canary --preid $(git branch --show-current)
lerna notice cli v4.0.0
lerna info versioning independent
lerna info canary enabled
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna info Looking for changed packages since cd8e3d09^..cd8e3d09
lerna success No changed packages to publish
✨  Done in 1.08s.
```

**Comment by NolanChan** [comment]
@dlasky am I doing this wrong? Whether or not I add a new commit, `yarn alpha` isn't pushing anything up

```
(stage-write/stage:us-west-2:centrifuge-destinations) $ yarn alpha
yarn run v1.22.19
$ lerna publish --canary --preid $(git branch --show-current)
lerna notice cli v4.0.0
lerna info versioning independent
lerna info canary enabled
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna info Looking for changed packages since cd8e3d09^..cd8e3d09
lerna success No changed packages to publish
✨  Done in 1.08s.
```

**Comment by dlasky** [comment]
did you make a meaningful change in the commit? if the resulting build has no deltas it wont push anything.

**Comment by NolanChan** [comment]
ah interesting! I just `touch`'d a random file so nothing showed up, that's cool that `alpha` will detect changed and not changed packages! 

```
(stage-write/stage:us-west-2:centrifuge-destinations) $ yarn alpha
yarn run v1.22.19
$ lerna publish --canary --preid $(git branch --show-current)
lerna notice cli v6.0.3
lerna info versioning independent
lerna info canary enabled
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna info Looking for changed packages since 3e77e363^..3e77e363

Found 1 package to publish:
 - @segment/action-destinations => 3.115.1-staging.6+3e77e363

? Are you sure you want to publish these packages? No
✨  Done in 13.49s.
```

**Review by NolanChan — APPROVED** [review]
tested locally!

**Pull request merged**
