### PR TITLE
Changing integration track payload

### PR DESCRIPTION
**Pull request by schung507**
Tweaking how we send data to Heap to reduce some friction with how our data works downstream. Payload type coming from Segment stays the same.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by murphpdx** [comment]
DO NOT MERGE; we are waiting for an ok from our customer.

**Comment by joe-ayoub-segment** [comment]
Hi @schung507 , acknowledging this PR. Will review ASAP.

**Comment by joe-ayoub-segment** [comment]
hi @schung507  and @murphpdx , can you let me know if this PR is still needed? If so I'll review.

**Review by joe-ayoub-segment — APPROVED** [review]
Hi @schung507 @murphpdx , 

This change looks good. 

Shall I merge it?

Joe

**Comment by murphpdx** [comment]
This is ready to merge

**Comment by joe-ayoub-segment** [comment]
Hi @schung507 , @murphpdx , this PR has been deployed

**Pull request merged**
