### PR TITLE
Update LaunchDarkly Action Destination to support event schema v4

### PR DESCRIPTION
**Pull request by ldhenry**
This PR updates the LaunchDarkly Action Destination to support LaunchDarkly's new event schema v4. This new schema allows for more customization and gives customers the ability to take full advantage of LaunchDarkly's new [Contexts feature](https://docs.launchdarkly.com/home/contexts).

Additional "context kind" fields with backwards compatible defaults were added to both actions.

- LaunchDarkly [Custom Event Schema](https://docs-stg.launchdarkly.com/contexts-eap/home/data-export/schema-reference#custom-events)

The `trackEvent` call has been improved for new customers as the anonymous ID will be associated with the user ID. For existing customers the integration will work as before and if they fill in the Additional Context keys setting to the recommended default they will get the same benefit.

The `aliasEvent` action has not changed. I have confirmed the existing payload is compatible with the v4 header.

CleanShot 2023-03-10 at 5 43 35@2x

## Testing

I added new tests and confirmed everything is working as intended using e2e testing.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @ldhenry , acknowledging your PR, thank you! I'll schedule time to review ASAP.

**Comment by joe-ayoub-segment** [comment]
Hi @ldhenry , 

Given the scope of this change would you be available to catch up with me for a face to face meeting please?
You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop

The main thing we want to avoid is potential disruption to ongoing customer data collection

Kind regards,
Joe

**Comment by ldhenry** [comment]
> Hi @ldhenry ,
> 
> Given the scope of this change would you be available to catch up with me for a face to face meeting please? You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop
> 
> The main thing we want to avoid is potential disruption to ongoing customer data collection
> 
> Kind regards, Joe

Just scheduled a meeting.

**Review by joe-ayoub-segment — CHANGES_REQUESTED** [review]
Hi @ldhenry , thank for meeting with me just now. Here are notes from our call. Please also see inline comments. 

During the call Henry and I did some end to end testing with the pre-existing Integration and the new version. We noticed some different behavior in the LaunchDarkly UI which Henry is going to check on. 

PR is to migrate to a new API

- API payload request schema has changed
- Body of payload is different
- Header is different 
- URL is the same

PR also adds capability to track ‘contexts’

- Basically allows for targeting of non user-scoped attributes. 

Notes on PR

- Addition of new field to automatically collect the anonymousId should not change the behavior for existing customers who already use the Integration. 
-- additional_context_keys.unauthenticatedUser
- The old version of the trackEvent Action collects only the userId or the anonymousId (not both) 
-- The new version of the trackEvent Action will collect both
-- However it’s not clear if the anonymousId and userId will be merged into the same profile. 
-- It might be a good idea to make this association happen when trackEvents are triggered as a lot of customers will expect this to occur irrespective of whether or not identify() calls are being fired.   
- Addition of required fields needs to be converted to optional fields
-- And ensure that new optional fields are defensively accessed (i.e check for undefined) as these fields will not have values for customers who are already using the Integration

Testing

- Please do some end to end tests with track() and identify() calls to ensure that behavior for existing customers doesn’t change 
- Please attach screenshots of tests

**Comment by joe-ayoub-segment** [comment]
hi @ldhenry , just checking in to see how you are going with testing, etc.

**Comment by ldhenry** [comment]
> hi @ldhenry , just checking in to see how you are going with testing, etc.

Hey @joe-ayoub-segment, a few things came up this week so I got a little behind. I'm working on it now though.

**Comment by ldhenry** [comment]
Hey @joe-ayoub-segment I just made the recommended fixes and included a screenshot showcasing the new version of the destination. Let me know if you would like to see any other changes or need any additional information.

**Comment by ldhenry** [comment]
Update: After some discussion with the team, we decided to not change the `aliasUser` action at this time. I have confirmed that the existing payload is compatible with the v4 header and the existing behavior is unchanged.

We may come back and update this at a later date but the team wanted to make some changes on our end first.

**Comment by joe-ayoub-segment** [comment]
Thanks @ldhenry I've scheduled time to look at this tomorrow. Will be in touch shortly.

**Comment by ldhenry** [comment]
> Thanks @ldhenry I've scheduled time to look at this tomorrow. Will be in touch shortly.

Hey @joe-ayoub-segment, do you think it would be possible to get this merged and deployed next week? One of our customers has asked about this.

Thanks,
Henry

**Review by joe-ayoub-segment — APPROVED** [review]
Reviewed and provided feedback. Changes were made and screenshots of tests provided. 
This is not adding any new required or pseudo-required fields. 
It is changing the API being posted to and also the payload - particularly with regards identifiers.

**Comment by joe-ayoub-segment** [comment]
hi @ldhenry , just waiting for CI to pass - we'll deploy next Wednesday.

**Comment by ldhenry** [comment]
> hi @ldhenry , just waiting for CI to pass - we'll deploy next Wednesday.

Great. Thanks for the update.

**Comment by joe-ayoub-segment** [comment]
hi @ldhenry this change has been deployed. 
Could you please confirm that things are as expected?

Kind regards,
Joe

**Pull request merged**
