### PR TITLE
[Usermaven] Fixed Created At Issue

### PR DESCRIPTION
**Pull request by seeratawan01**
In this PR we added missing created at field to the payload and also added additional check if the company id is present in the payload.

Kindly Please merge this PR in upcoming release.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @seeratawan01 , 
Thanks for the PR - I'll review ASAP.

**Review by joe-ayoub-segment — APPROVED** [review]
Looks good. 
Tests pass. Validate passes. 
No field changes.

**Comment by seeratawan01** [comment]
Thanks @joe-ayoub-segment,

It would be great if you merge it with today's release.

**Comment by joe-ayoub-segment** [comment]
Merged. This should go out with the next deploy - hopefully today.

**Comment by seeratawan01** [comment]
Perfect, thanks!

**Comment by joe-ayoub-segment** [comment]
Hi @seeratawan01 this has been deployed. Please check and let me know if everything looks OK!

**Pull request merged**
