### PR TITLE
SD-91672 | Optins added | Insider Destination

### PR DESCRIPTION
**Pull request by emreisik95**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 thanks for raising the PR. I'll schedule for review.

**Review by joe-ayoub-segment — APPROVED** [review]
Looks good to me. Just need to make sure CI passes.

**Comment by emreisik95** [comment]
> Looks good to me. Just need to make sure CI passes.

Awesome news. Can we merge it directly or should we wait for the next deployment?

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 I won't merge it yet as it will need a DB update when it has been deployed. If I merge it now and another Developer deploys it they won't think to do the DB update. 

I'll merge it once I start preparing the deploy. 
Thanks
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 , 
There's a flakey test from another Integration which is causing this PR to fail CI tests. 
The test has been fixed, but you'll need to get the latest changes from the main branch before your PR will pass CI checks. 
Can you do this please?
Thanks,
Joe

**Comment by emreisik95** [comment]
> Hi @emreisik95 , There's a flakey test from another Integration which is causing this PR to fail CI tests. The test has been fixed, but you'll need to get the latest changes from the main branch before your PR will pass CI checks. Can you do this please? Thanks, Joe

Hello Joe,

I've updated the branch. Thanks for information.

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 , we're looking to do the deploy tomorrow. It was postponed from today unfortunately.

**Pull request merged**
