### PR TITLE
Track event name changes

### PR DESCRIPTION
**Pull request by esezerguven**
On our system we only except the event names under_lined and without spaces and lowercase. We convert the segment names.

## Testing

We send request as event name 'Segment Test Event' and it is converted on our side as 'segment_event-test'

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by esezerguven** [comment]
> hello @esezerguven, could you update the description of the PR?

hello I have updated. Please let me know if something is missing thanks.

**Comment by rhall-twilio** [comment]
@esezerguven it looks like some testcases are failing

**Comment by esezerguven** [comment]
> @esezerguven it looks like some testcases are failing

I have updated unit test they should pass right now @rhall-twilio. After updates we tested again on our local fyi.

**Review by rhall-twilio — APPROVED** [review]

**Comment by esezerguven** [comment]
@rhall-twilio is it live ? Or it take time to publish

**Pull request merged**
