### PR TITLE
Adding logic to not double-hash the email when already hashed.

### PR DESCRIPTION
**Pull request by seg-leonelsanches**
Several clients are asking this since they don't send their customers' profile email as plain information.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [X] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by nick-Ag** [comment]
@seg-leonelsanches Could we add a unit test for this? Otherwise looks good

**Comment by seg-leonelsanches** [comment]
> @seg-leonelsanches Could we add a unit test for this? Otherwise looks good

Okay, added :)

Thanks for the review.

**Review by nick-Ag — APPROVED** [review]
🚀

**Comment by joe-ayoub-segment** [comment]
Hi @seg-leonelsanches this PR was deployed. No Push was done

**Comment by seg-leonelsanches** [comment]
> Hi @seg-leonelsanches this PR was deployed. No Push was done

Thank you, @joe-ayoub-segment

**Pull request merged**
