### PR TITLE
Update Ripe web destination

### PR DESCRIPTION
**Pull request by simpajj**
- Add new endpoint setting for testing purposes
- Remove alias call as we're not using it
- Update misleading anonymousId descriptions
- Map anonymousId in identify call
- Update default paths

----

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
notes for @pooyaj : 

I met with them last week and did a black box review of their web integration, and recommended some changes. Looks like they just submitted a PR for those changes. Looks good to me, but I think you need to review, approve, merge.

**Review by pooyaj — COMMENTED** [review]
can we do `settings.endpoint || 'https://storage.getripe.com'` instead? This is due to some limitations on our end where the code update may go out before we update the destination definition ( which contains the default value for the endpoint )

**Comment by simpajj** [comment]
> can we do `settings.endpoint || 'https://storage.getripe.com'` instead? This is due to some limitations on our end where the code update may go out before we update the destination definition ( which contains the default value for the endpoint ) and therefore, there could be a window of time where settings.endpoint is undefined.

Sure thing! Updated it now.

**Review by pooyaj — APPROVED** [review]

**Comment by simpajj** [comment]
@pooyaj noticed a failing test that I've fixed now

**Comment by simpajj** [comment]
Hi @pooyaj 
Any updates on this?

**Comment by joe-ayoub-segment** [comment]
Confirmed with @pooyaj that this is OK to merge and deploy.

**Comment by joe-ayoub-segment** [comment]
Confirmed with Pooja that this can be merged and deployed

**Review by joe-ayoub-segment — COMMENTED** [review]
Pooja confirmed this looks good.

**Comment by joe-ayoub-segment** [comment]
Hi @simpajj , 
The change was deployed last week. Could you please check that everything works as expected and comment here please?
Thank you !

**Pull request merged**
