### PR TITLE
Added key value pair of new regional endpoint

### PR DESCRIPTION
**Pull request by mishranik**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @mishranik - CI is still failing. Could you pull all the latest changes from the main branch into your branch please?

**Comment by mishranik** [comment]
@joe-ayoub-segment I did that, and it is showing me up-to-date. 

image

**Comment by joe-ayoub-segment** [comment]
image

Hi @mishranik can you update this test please?

**Comment by mishranik** [comment]
@joe-ayoub-segment done.

**Comment by joe-ayoub-segment** [comment]
Thanks @mishranik - looks good!

**Comment by joe-ayoub-segment** [comment]
Hi @mishranik this PR has been deployed. Can you please let me know if you are happy with the changes?

**Pull request merged**
