### PR TITLE
SD-96364 |  Madeira Madeira | Data sent by Segment is not reaching Insider.

### PR DESCRIPTION
**Pull request by emreisik95**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks for raising this PR @emreisik95 . I'll schedule for review.

**Comment by emreisik95** [comment]
@joe-ayoub-segment Is there an estimated deployment time we can give to the partner?

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 , the earliest we'll be able to get this reviewed, merged and deployed will be next Tuesday 24-Oct-2023. 
Can we line up some time later this week (Friday maybe) to catch up and review the PR together? If any changes need to be made then we can merge them in then? 

Here's my Calendly link where you can schedule a call: http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 thanks for raising this PR. 

2 main comments to discuss. 

1. If you have customers using the Integration already, we can't add a new 'required' field. It will break data collection for those customers. Instead, if you could make this field optional, and then you should access that field defensively ( check for it being undefined before you try to access the field value). 

2. The 2 new functions sendBulkTrackEvents and bulkUserProfilePayload seem to deviate a lot from the sendTrackEvent and userProfilePayload functions. I'm finding the code / logic in these functions difficult to follow.  Shouldn't the logic be practically the same as the functions which handle individual event payloads, except for the batch versions return an array?

**Comment by emreisik95** [comment]
Hello @joe-ayoub-segment,

1. Actually we thought here optional. I will fix. 
2. I will refactor those functions, it will be more understandable. I am planning the complete it before our meet.

**Comment by joe-ayoub-segment** [comment]
> Hello @joe-ayoub-segment,
> 
> 1. Actually we thought here optional. I will fix.
> 2. I will refactor those functions, it will be more understandable. I am planning the complete it before our meet.
> 
> Thanks, Emre

Thanks Emre, 
You can actually just remove the enable_batching field completely. Batching will be enabled if you simply implement the performBatch() function.

**Comment by emreisik95** [comment]
Hello @joe-ayoub-segment,

I removed enable_batching field and refactored the sendBulkTrackEvents. But I believe bulkUserProfilePayload can stay like this, this function transforming the segment payload to insider payload, and eliminating the empty values. We can discuss it if needed. 

Thanks,
Emre

**Review by joe-ayoub-segment — APPROVED** [review]
Discussed this PR in person with @emreisik95 . 
Explained that the code that builds the payloads is overly complex and difficult to understand/follow, and that I recommended a refactor. @emreisik95 agreed to refactor post deploy of this PR, and accepted any potential risk associated with deploying this PR.

**Comment by joe-ayoub-segment** [comment]
Hi @emreisik95 - PR deployed. Please confirm that everything works as expected!

**Pull request merged**
