### PR TITLE
Move event name field, update required fields for StackAdapt destination

### PR DESCRIPTION
**Pull request by AlliterativeAlice**
A few small updates based on beta testing feedback with customers:
- Make user agent and IP fields required as without these conversions cannot be attributed successfully.
- Made user ID field not required as we can track conversions without it.
- Move "event name" field out of ecommerce fields and into the first-level fields, as it is used outside ecommerce use cases.

## Testing

Validated that the field changes above were reflected in the mapping UI:

image

image

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
  - Updated snapshot due to changing required fields, no other test changes needed as functionality did not change, only field configuration.
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @AlliterativeAlice thanks for raising this PR. 

The code looks good. If CI checks pass I'll deploy Tuesday. 

One important thing: changing a field from being 'not required' to 'required' will cause the Destination to break for any customers who already have it configured. Is that OK with you? Does the customer who is doing testing understand this?

Post deploy the customer can just re-add the Destination and configure it and it will work.  

Please let me know if you'd like me to proceed to deploy.

**Comment by AlliterativeAlice** [comment]
> hi @AlliterativeAlice thanks for raising this PR.
> 
> The code looks good. If CI checks pass I'll deploy Tuesday.
> 
> One important thing: changing a field from being 'not required' to 'required' will cause the Destination to break for any customers who already have it configured. Is that OK with you? Does the customer who is doing testing understand this?
> 
> Post deploy the customer can just re-add the Destination and configure it and it will work.
> 
> Please let me know if you'd like me to proceed to deploy.

Yes, please proceed with deploying on Tuesday. We are okay with that as calls sent to our destination without IP and user agent will fail anyway. We have informed our customer that IP and user agent are required and we will inform them that we will be marking these fields required as well.

**Comment by joe-ayoub-segment** [comment]
Hi @AlliterativeAlice - PR deployed. Please confirm that the change looks good to you!

**Comment by AlliterativeAlice** [comment]
> Hi @AlliterativeAlice - PR deployed. Please confirm that the change looks good to you!

Thanks Joe, I have confirmed the field changes are reflected in our destination.

**Pull request merged**
