### PR TITLE
PlayerZero Cloud Destination

### PR DESCRIPTION
**Pull request by colin4554**
This adds a PlayerZero Cloud Detestation so we can support customers that use Segment Cloud. The cloud destination simply forwards raw segment events to PlayerZero where we do further processing with more context. 

Additionally, this updates some language on our Device Destination to remain consistent with our product.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @colin4554 , 

Thank you for raising this PR for both a bug fix to the existing playerzero-web Destination and the creation of a new playerzero-cloud Destination! 

Could you please separate the playerzero-web bug fix into a different PR please? 

I had an initial look at the playerzero-web change and can see that you are removing the projectId field and adding a new field called projectToken.  Doing this is going to break the data collection for anyone who already has this Integration configured. 

It's perfectly fine to change the label and description of a field, but removing or adding fields will break stuff for customers. 

For new Integrations I usually request a meeting so I can get an understanding of the use-cases for the Integration, and to discuss identifiers, event payloads, etc. This will help me provide you with better feedback when I review the PR for the new Integration. Would you be open to this? 

If so, here's how you can schedule a call with me: http://calendly.com/joe_ayoub/integration-workshop 

Best regards,
Joe

**Review by joe-ayoub-segment — APPROVED** [review]
Thanks for taking the time to meet @colin4554 , and for applying the change we discussed. 
Approved.

**Comment by joe-ayoub-segment** [comment]
Hi @colin4554 , could you take a look at this CI check which failed please?

image

**Comment by joe-ayoub-segment** [comment]
Hi @colin4554 , can you make the following change please ini the util.ts file?

Change this: 

import { RequestClient } from '@segment/actions-core/dist/cjs'

to this: 

import type { ActionDefinition } from '@segment/actions-core'

Thank you, 
Joe

**Comment by colin4554** [comment]
> Hi @colin4554 , can you make the following change please ini the util.ts file?
> 
> Change this:
> 
> import { RequestClient } from '@segment/actions-core/dist/cjs'
> 
> to this:
> 
> import type { ActionDefinition } from '@segment/actions-core'
> 
> Thank you, Joe

Hey @joe-ayoub-segment, I'm assuming you meant to change it to `import type { RequestClient } from '@segment/actions-core'` so the import still works.

I made that change, let me know if there is anything else or if I interpreted that wrong.

Thanks, Colin

**Comment by joe-ayoub-segment** [comment]
Thanks @colin4554 we're good. We'll deploy tomorrow. 
Best regards,
Joe

**Comment by joe-ayoub-segment** [comment]
Hi @colin4554 this PR has been deployed - I'll email you next steps.

**Pull request merged**
