### PR TITLE
fix(Jimo): resolve when jimo is not an array & remove manualInit from settings

### PR DESCRIPTION
**Pull request by imsamdez**
- Correctly resolve jimo at initialization
- Remove manualInit from the setting parameters

Also, i'm not sure why the PR seems to include previous jimo commits that has been already merged even if I synchronized my fork before doing my changes. Sorry about that, let me know if I can fix this.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @imsamdez , 

Was the manualInit setting referenced anywhere in the code base? Have all references to it been removed?

Best regards.
Joe

**Comment by imsamdez** [comment]
> Hi @imsamdez ,
> 
> Was the manualInit setting referenced anywhere in the code base? Have all references to it been removed?
> 
> Best regards. Joe

Now, yes 😅

Best,
Sam.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @imsamdez , 

Apologies for the late notice, but we had to roll back this week's Web deploy due to an issue with some code which resulted in an incident. 

It was unrelated to this PR, however we needed to roll back everything. We plan to deploy the code again across Monday/Tuesday next week. 

Apologies again for the inconvenience. 
Joe

**Comment by imsamdez** [comment]
Hey @joe-ayoub-segment,

Any updates about this?
Just made some test and can't make it work, was wondering if it got deployed in the past few days.

Thanks.

**Comment by joe-ayoub-segment** [comment]
Hi @imsamdez , 

The deployment was completed last night. 
I can see that the new code is live. You can view it here: https://cdn.segment.com/next-integrations/actions/jimo/ccefac19c8888fb101b9.js 

Can you try setting up a new Destination please? 

Feel free to schedule a call and I can take a look: http://calendly.com/joe_ayoub/integration-workshop 

Best regards,
Joe

**Pull request merged**
