### PR TITLE
Dynamic Yield: fix for non standard identifiers

### PR DESCRIPTION
**Pull request by joe-ayoub-segment**
Fix bug for non userId or email identifiers for Dynamic Yield Destination

## Testing

Tested locally.

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
```
INFO: Listening at http://localhost:3000 -> 
  POST /authenticate
  POST /createAudience
  POST /getAudience
  POST /refreshAccessToken
  POST /syncAudience

INFO: 💬  304 GET /manifest - 2ms
{
  "type": "audience_membership_change_request",
  "id": "personas_2j6KyRohsanc9qDfbAKZ1Djq8pB",
  "timestamp_ms": 1720702340228,
  "account": {
    "account_settings": {
      "section_id": "sdfsdfsd",
      "identifier_type": "userid",
      "accessKey": "sdfsdfssdfsdfsddfgdfgfdg"
    }
  },
  "user_profiles": [
    {
      "user_identities": [
        {
          "type": "userid",
          "encoding": "raw",
          "value": "user1572"
        }
      ],
      "audiences": [
        {
          "audience_id": 8794123497119088,
          "audience_name": "test",
          "action": "add"
        }
      ]
    }
  ]
}
```

**Comment by joe-ayoub-segment** [comment]
```

INFO: Listening at http://localhost:3000 -> 
  POST /authenticate
  POST /createAudience
  POST /getAudience
  POST /refreshAccessToken
  POST /syncAudience

INFO: 💬  304 GET /manifest - 2ms
{
  "type": "audience_membership_change_request",
  "id": "personas_2j6KyRohsanc9qDfbAKZ1Djq8pB",
  "timestamp_ms": 1720702340228,
  "account": {
    "account_settings": {
      "section_id": "sdfsdfsd",
      "identifier_type": "email",
      "accessKey": "sdfsdfssdfsdfsddfgdfgfdg"
    }
  },
  "user_profiles": [
    {
      "user_identities": [
        {
          "type": "email",
          "encoding": "\"sha-256\"",
          "value": "e2daf49e7053931a9c29eb16e14fcff49107f5107ea5f6cc4a1313486e16d27f"
        }
      ],
      "audiences": [
        {
          "audience_id": 8794123497119088,
          "audience_name": "test",
          "action": "add"
        }
      ]
    }
  ]
}

```

**Comment by joe-ayoub-segment** [comment]
```

INFO: Listening at http://localhost:3000 -> 
  POST /authenticate
  POST /createAudience
  POST /getAudience
  POST /refreshAccessToken
  POST /syncAudience

INFO: 💬  304 GET /manifest - 9ms
{
  "type": "audience_membership_change_request",
  "id": "personas_2j6KyRohsanc9qDfbAKZ1Djq8pB",
  "timestamp_ms": 1720702340228,
  "account": {
    "account_settings": {
      "section_id": "sdfsdfsd",
      "identifier_type": "ios.id",
      "accessKey": "sdfsdfssdfsdfsddfgdfgfdg"
    }
  },
  "user_profiles": [
    {
      "user_identities": [
        {
          "type": "ios.id",
          "encoding": "raw",
          "value": "device_id_1572"
        }
      ],
      "audiences": [
        {
          "audience_id": 8794123497119088,
          "audience_name": "test",
          "action": "add"
        }
      ]
    }
  ]
}
```

**Review by sayan-das-in — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
PR deployed.

**Pull request merged**
