### PR TITLE
Braze regions

### PR DESCRIPTION
**Pull request by davidbielik**
_Adds upcoming Braze regions_

## Testing

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @davidbielik thanks for raising this PR. 
I noticed you said 'upcoming' in your description. Is it ready to go live?

**Comment by joe-ayoub-segment** [comment]
hi again @davidbielik looks like some CI checks failed. Any chance you could take a look please?

**Comment by davidbielik** [comment]
Hi @joe-ayoub-segment the tests fail in the Install Dependencies step, which seems unrelated:

> Error: ENOENT: no such file or directory, open '/home/runner/.cache/yarn/v6/npm-@segment-control-plane-service-client-9.3.0-e5cd6e7cd335cf00640e43a5ece17a290e003ddd/node_modules/@segment/control-plane-service-client/.yarn-metadata.json'

Can you confirm?

These changes are ready to merge.

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @davidbielik this PR has been deployed. Please confirm you are happy with the change.

**Comment by davidbielik** [comment]
Yes, thanks!

**Pull request merged**
