### PR TITLE
[Amazon AMC] - Revamp Refresh Token Flow for createAudience and getAudience

### PR DESCRIPTION
**Pull request by Innovative-GauravKochar**
**Issue :-**  When token gets expired ,sync was getting failed , no audience was getting created and no events were sent to destination as refresh token flow does not apply for createAudience and getAudience methods.

This Pull request is to revamp refresh access token flow for createAudience and getAudience in Amazon AMC (Actions). Now if token gets expired , it doesn't create any issue in further syncing.

Jira ticket:- https://segment.atlassian.net/browse/STRATCONN-3792
Screenshot 2024-06-11 at 10 39 41 PM

Screenshot 2024-06-11 at 10 39 09 PM

Screenshot 2024-06-11 at 10 38 57 PM

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by varadarajan-tw — APPROVED** [review]
LGTM! Let's try to bake refreshAccessToken flow into the framework for createAudience and getAudience in the next PR.

**Comment by joe-ayoub-segment** [comment]
hi @varadarajan-tw I think refreshAccessToken not being called automatically for getAudience and createAudience is a bug we need to fix with high priority as there are other Audience Destinations which will rely on it. 
   
Personally I had assumed that it would be called, so it's good to know that this isn't the case so it can be fixed.

**Comment by joe-ayoub-segment** [comment]
Also has this PR been deployed?

**Comment by varadarajan-tw** [comment]
Yes. This PR has been deployed.

**Pull request merged**
