### PR TITLE
schematic - remove locked property name for userId

### PR DESCRIPTION
**Pull request by jasdeepg**
removed properties from user_keys for both actions. the desired behavior is that the user can choose the property name, not that we assume/lock one.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @tcgilbert will you be taking this PR?

**Review by tcgilbert — APPROVED** [review]
LGTM

**Review by joe-ayoub-segment — APPROVED** [review]
Reviewed by Thomas - approved

**Comment by joe-ayoub-segment** [comment]
hi @jasdeepg this PR has been deployed

**Comment by jasdeepg** [comment]
thank you @joe-ayoub-segment !

**Pull request merged**
