### PR TITLE
fix(Jimo): return a intermediary object to prevent mutation of object…

### PR DESCRIPTION
**Pull request by imsamdez**
Returns an object instead of the sdk itself to prevent Segment losing control over the SDK because of mutation

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by imsamdez** [comment]
Hey @joe-ayoub-segment,

Do you know if this is going to be deployed tomorrow?

Best,
Sam.

**Comment by joe-ayoub-segment** [comment]
hi @imsamdez the CI is failing. I don't have the time to look into it right now though. 
I'm hoping to get to it later once I've completed some other tasks. 

Best regards,
Joe

**Comment by imsamdez** [comment]
@joe-ayoub-segment Let me check if i can get them to fail locally and fix them.

**Comment by imsamdez** [comment]
Re @joe-ayoub-segment, I merged main and fixed tests. We should be good now!

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @imsamdez this PR has been deployed. Please confirm it does what you expect!

**Pull request merged**
