### PR TITLE
Add logrocket browser destination

### PR DESCRIPTION
**Pull request by nminchow**
This PR adds the LogRocket browser destination with support for sdk initialization, identify, and track calls.

## Testing

Reviewers: You can use `noel-org/segment-app-public` as a logrocket app ID to see events firing.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Review by pooyaj — APPROVED** [review]
Looks great 🙌

**Comment by nminchow** [comment]
Ah - it doesn't look like the test suite likes my test utility files in those directories. Is there somewhere else I should be putting those?

**Comment by pooyaj** [comment]
@nminchow yes, looks like not happy about the tests. Let's put all test utilities in a single file at the root folder for your destination.

**Comment by pooyaj** [comment]
@nminchow looks like Typescript errors in the CI 👀

**Comment by nminchow** [comment]
> @nminchow looks like Typescript errors in the CI 👀

Yeah - it looks like its because I pulled my test mocking behavior out of the test folders. I'll see what I can do

**Review by pooyaj — APPROVED** [review]

**Pull request merged**
