### PR TITLE
Trackey integration

### PR DESCRIPTION
**Pull request by clickoutio**
The [Trackey](https://www.trackey.io) cloud destination segment integration integration. 
We have three different actions. One for the identify, track and group events. 

We don't do any mapping, because the backend can take it directly.

## Testing
- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
hi @clickoutio thanks for raising this PR. Given that it's for a new Integration would you be OK meeting to discuss the use-cases for it and the implementation as well please?

You can schedule a call with me here http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

**Comment by clickoutio** [comment]
Hi Joe, I have scheduled a call for tomorrow at 12:30 CEST. 

Best regards,
Javi

**Comment by joe-ayoub-segment** [comment]
Hi @clickoutio , just checking if you are still interested in progressing with this PR? Happy to sync up and get whatever changes we need done in a call, and then get this merged and deployed. Please let me know. 

You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

**Comment by clickoutio** [comment]
Hi Joe, we have been doing some changes in our backend infrastructure and we wanted to have that finished before finishing the segment integration. I think now everything is done. Tell me if something is missing.

Best regards,
Javier

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @clickoutio I had some recommendations from the review, but decided to approve and merge anyway as long as the CI checks pass. 
I'll fix up a couple of minor things and hopefully get it deployed today!

**Comment by joe-ayoub-segment** [comment]
Hi @clickoutio I've deployed this Integration. I've emailed you with next steps / instructions. 
Best regards,
Joe

**Pull request merged**
