### PR TITLE
Updated field's description and commented out performBatch

### PR DESCRIPTION
**Pull request by akansal1599**
Updated the action field's description as per the earlier PR comments. Commented out `performBatch`.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @akansal1599 , 
There are failing unit tests. Any chance you could take a look please?
image

**Comment by akansal1599** [comment]
Hi @joe-ayoub-segment , I have commented out the performBatch unit test and updated snapshots. It should work now.

**Review by joe-ayoub-segment — APPROVED** [review]
Looks good.

**Comment by joe-ayoub-segment** [comment]
hi @akansal1599 , there are failing unit tests in this PR. They don't seem to be directly because of the code you added though. I'm wondering if you could bring your branch up to date with segmentio/action-destinations main branch please? It might fix the issue.

**Comment by akansal1599** [comment]
Hi @joe-ayoub-segment , I have updated the current branch with segmentio/action-destinations main branch. I hope this fixes the issue.

**Comment by joe-ayoub-segment** [comment]
Thanks @akansal1599 I'll run the tests and let you know.

**Comment by joe-ayoub-segment** [comment]
hi @akansal1599 looks like that might have done the trick. However we have some other issues which are preventing the tests from passing. Our team here will look into those.

**Pull request merged**
