### PR TITLE
IQM Destination

### PR DESCRIPTION
**Pull request by alexeyiqm**
IQM Destination for Segment.io

A new destination for segment.io for the IQM platform for conversion tracking.

## Testing

Tested all the endpoints using local Segment CLI, and tested all the IQM endpoints.

- [ x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ x] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Hi @alexeyiqm , 
Thanks for raising this PR for a new Integration. 
Our standard process for new Integrations is to have a meeting with you so I can get an understanding of the key use-cases for this Integration. I'd also like to discuss the types of payloads this Integration will handle, and the identifiers it needs. 

Would you be OK scheduling a call with me for later this week?

http://calendly.com/joe_ayoub/integration-workshop

Kind regards,
Joe

**Comment by alexeyiqm** [comment]
Hi Joe,

Sure, scheduled

Thank you

**Comment by joe-ayoub-segment** [comment]
Hi @alexeyiqm thanks for raising this PR! I'll schedule for review.

**Review by joe-ayoub-segment — APPROVED** [review]
Thanks for taking the time to catch up just now @alexeyiqm , and for applying the changes we discussed. 
Approved.

**Comment by joe-ayoub-segment** [comment]
hi @alexeyiqm this PR has been deployed. I'll email you with next steps.

**Pull request merged**
