### PR TITLE
Adjust timestamps for consistency with other destinations

### PR DESCRIPTION
**Pull request by marcio-absmartly**
This PR changes the timestamp calculation. Before we passing the original timestamps from and doing the same calculations later on our collector, however, this could lead to descrepancies in timestamp on multiple destinations. This chance turns on the historical flag, and adjusts timestamps before sending to ensure the timestamp persisted in ABsmartly is the same as Segment's event `timestamp`

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks for raising this PR @marcio-absmartly . I'll schedule for review.

**Comment by joe-ayoub-segment** [comment]
hi @marcio-absmartly - apologies for being so slow to get this this PR. We've been in a lengthy code freeze which is ending tomorrow. 

I noticed a couple of issues with this PR. 

The PR effectively adds a new 'required' field (exposedAt) and removes a pre-existing required field (publishedAt). Add a new required field will break data collection for any customer who is already using the integration. The settings they will have saved to the DB will know nothing about the new 'required' field which has been added, so it will resolve to undefined at run time, and then all their data will be blocked from being processed. 

It's far easier and safer to reuse the pre-existing field, but to treat it differently in code - if that makes sense. 
Alternatively, you could add a new 'optional' field, which won't break data collection for customers who are already using the Integration.

**Comment by joe-ayoub-segment** [comment]
It might be quicker to get this updated in a 1:1 meeting? Feel free to schedule a call with me http://calendly.com/joe_ayoub/integration-workshop

**Comment by joe-ayoub-segment** [comment]
Hi @marcio-absmartly , 
following up on this. Is this change still something you'd like to progress with? if so, there's some feedback to take into account. If you are unsure of what to do, feel free to schedule a call with me http://calendly.com/joe_ayoub/integration-workshop

There are only a limited number of deploy slots remaining this year, with the next one being this Wednesday. So if you want to get the code out then we should meet soon. 

Best regards,
Joe

**Comment by marcio-absmartly** [comment]
> Hi @marcio-absmartly , following up on this. Is this change still something you'd like to progress with? if so, there's some feedback to take into account. If you are unsure of what to do, feel free to schedule a call with me http://calendly.com/joe_ayoub/integration-workshop
> 
> There are only a limited number of deploy slots remaining this year, with the next one being this Wednesday. So if you want to get the code out then we should meet soon.
> 
> Best regards, Joe

I have booked a meeting tomorrow.

Thanks Joe

**Comment by marcio-absmartly** [comment]
Hey @joe-ayoub-segment, just applied the changes we discussed.
Please give it a look to be sure, but I think everything should be good for deployment.

**Comment by joe-ayoub-segment** [comment]
Hi @marcio-absmartly , thanks for updating the PR. 

I can see that there's an issue with the code though. If you run 'yarn build' you will see it. 

image

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
Hi @marcio-absmartly this PR has been deployed. Can you please test and confirm that it works as expected please?

**Comment by marcio-absmartly** [comment]
Hi Joe,

Everything seems to be working fine. Thanks!

**Pull request merged**
