### PR TITLE
Adding batch to events

### PR DESCRIPTION
**Pull request by Romani-Ramzi**
_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

### CODE REVIEW

**Comment by joe-ayoub-segment** [comment]
Thanks for raising this PR @Romani-Ramzi . I'll schedule for review

**Comment by joe-ayoub-segment** [comment]
hi @Romani-Ramzi looks like a bunch of CI checks are failing. Can you take a look please?
If it's not your code change then try merging in the latest code form the Segment action-destinations main branch.

**Comment by joe-ayoub-segment** [comment]
hi @Romani-Ramzi there's an issue with our CI on Github. It's likely the cause of the red CI checks. The team is on it.

**Comment by Romani-Ramzi** [comment]
@joe-ayoub-segment is there any update regarding this PR?

**Comment by joe-ayoub-segment** [comment]
hi @Romani-Ramzi I'll review this today. 
In the meantime - CI checks appear to be failing. Any chance you could take a look please?

**Review by joe-ayoub-segment — CHANGES_REQUESTED** [review]
hi @Romani-Ramzi 
I just reviewed the code and it looks like a straightforward change.

Would you be able to attach evidence of testing each of these Actions with an array of payload events please (being sent to your batch endpoint)?

Also, it seems like some of the Actions have these 2 fields aded but the others don't.

Could they be added to all Actions please?

    enable_batching: {
      label: 'Enable Batching',
      description: 'Enable batching of event data to Optimizely.',
      type: 'boolean',
      default: true,
      unsafe_hidden: true
    },
    batch_size: {
      label: 'Batch Size',
      description: 'Number of events to batch before sending to Optimizely.',
      type: 'integer',
      default: 100,
      unsafe_hidden: true
    }

Remember to run the ./bin/run generate:types command afterwards and to commit the changes. 

Last thing is to make sure the CI checks are passing. 

If you can get this all done by tomorrow I can include this in tomorrow's deploy. 

Best regards,
Joe

**Comment by Romani-Ramzi** [comment]
@joe-ayoub-segment we updated to fix all test and missing "batch" configuration fields.
there are test for batch that we expected to fail, but it did not, we just put a comment "/// TODO" next to them.

In batch test, we though that it should throw error if required field is missing.
also in profile action, in single request, address object is excluded if there is no address, but in batch seems to appear with empty object.

please advice.

**Comment by joe-ayoub-segment** [comment]
hi @Romani-Ramzi , 

Sorry, I should have been more clear in my request ;)!

There are 4 Actions being updated so that they can support batching. 
What I'd like to see evidence of is that each Action can be called with an array of payloads, and that the delivery of those payloads is successful to Optimizely. 

Another thing I noticed is that it looks like some of the generated-types.ts files were not updated despite new fields being added. You might need to run the `./bin/run generate:types` command and commit the edit. 

Lastly we need to see that the CI checks are green. It's possible that just updating the types will fix this, but I can't be sure. 

Kind regards,
Joe

**Comment by Romani-Ramzi** [comment]
@joe-ayoub-segment 
my mistake, I was pushing to different branch, I accidently pushed to different branch name, but its fixed now.

**Comment by Romani-Ramzi** [comment]
CustomEvent Action end-to-end Test:

SegmentIO side:
Screenshot 2024-08-15 084710


Optimizely side:
Screenshot 2024-08-15 084913

Got request as array.

**Comment by Romani-Ramzi** [comment]
nonEcommCustomEvent Action end-to-end Test:

SegmentIO side:
Screenshot 2024-08-15 101139

Optimizely side:
Screenshot 2024-08-15 101025

Got request as array.

**Comment by Romani-Ramzi** [comment]
emailEvent Action end-to-end Test:

SegmentIO side:
Screenshot 2024-08-15 101648

Optimizely side:
Screenshot 2024-08-15 101429

Got request as array.

**Comment by Romani-Ramzi** [comment]
upsertContact Action end-to-end Test:

SegmentIO side:
Screenshot 2024-08-15 102153

Optimizely side:
Screenshot 2024-08-15 102107

Got request as array.

**Review by joe-ayoub-segment — DISMISSED** [review]

**Review by joe-ayoub-segment — APPROVED** [review]

**Comment by joe-ayoub-segment** [comment]
hi @Romani-Ramzi this PR has been deployed. Can you please confirm it looks good?

**Pull request merged**
